Repository tektoncd/chains, pull requests merged in 2020-06, with the labels that each got.

#1 Add boilerplate repo documentation.
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  ROADMAP.md
  code-of-conduct.md
Labels: size/L

#3 Actually fix links
  README.md
Labels: lgtm, size/XS

#2 Add initial OWNERS file.
  OWNERS
Labels: do-not-merge/invalid-owners-file, size/XS

#4 Add boilerplate Go modules and test hooks.
  go.mod
  go.sum
  hack/tools.go
  test/presubmit-tests.sh
  vendor/github.com/tektoncd/plumbing/.yamllint
  vendor/github.com/tektoncd/plumbing/CONTRIBUTING.md
  vendor/github.com/tektoncd/plumbing/DEVELOPMENT.md
  vendor/github.com/tektoncd/plumbing/LICENSE
  vendor/github.com/tektoncd/plumbing/Makefile
  vendor/github.com/tektoncd/plumbing/OWNERS
  vendor/github.com/tektoncd/plumbing/README.md
  vendor/github.com/tektoncd/plumbing/addpermissions.py
  vendor/github.com/tektoncd/plumbing/code-of-conduct.md
  vendor/github.com/tektoncd/plumbing/demo
  vendor/github.com/tektoncd/plumbing/dummy.go
  vendor/github.com/tektoncd/plumbing/go.mod
  vendor/github.com/tektoncd/plumbing/go.sum
  vendor/github.com/tektoncd/plumbing/roadmap.md
  vendor/github.com/tektoncd/plumbing/scripts/README.md
  vendor/github.com/tektoncd/plumbing/scripts/dummy.go
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/markdown-link-check-config.rc
  vendor/github.com/tektoncd/plumbing/scripts/markdown-lint-config.rc
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#5 Fix markdown link typo in README
  README.md
Labels: approved, lgtm, size/XS

#7 Tweak the golang-ci config
  .golang-ci.yaml
  test/presubmit-tests.sh
Labels: approved, lgtm, size/M

#10 Add skelterjohn to the OWNERS file.
  OWNERS
Labels: approved, lgtm, size/XS

#11 Remove sbwsg and dibyom from list of owners
  OWNERS
Labels: approved, lgtm, size/XS
