Repository tektoncd/chains, pull requests merged in 2020-07, with the labels that each got.

#9 Add and wire up the signing interfaces.
  cmd/controller/main.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/signing/formats/format.go
  pkg/signing/formats/tekton.go
  pkg/signing/formats/tekton_test.go
  pkg/signing/signing.go
  pkg/signing/signing_test.go
Labels: approved, lgtm, size/L

#15 Only store the TaskRun.Status for Tekton payload types.
  pkg/signing/formats/tekton.go
  pkg/signing/formats/tekton_test.go
Labels: approved, lgtm, size/XS

#17 Add boilerplate for the signing secrets.
  config/100-deployment.yaml
Labels: approved, lgtm, size/S

#16 Add and wire up a storage interface.
  cmd/controller/main.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/signing/signing.go
  pkg/signing/signing_test.go
  pkg/signing/storage/storage.go
  pkg/signing/storage/tekton/tekton.go
  pkg/signing/storage/tekton/tekton_test.go
Labels: approved, lgtm, size/L

#18 Use patch instead of update to mutate annotations.
  pkg/patch/patch.go
  pkg/patch/patch_test.go
  pkg/signing/signing.go
  pkg/signing/signing_test.go
  pkg/signing/storage/tekton/tekton.go
Labels: approved, lgtm, size/L

#19 Add a package to PGP sign data.
  go.mod
  pkg/controller/controller.go
  pkg/signing/pgp/pgp.go
  pkg/signing/pgp/pgp_test.go
  pkg/signing/pgp/testdata/README.md
  pkg/signing/pgp/testdata/pgp.passphrase
  pkg/signing/pgp/testdata/pgp.private-key
  pkg/signing/pgp/testdata/pgp.public-key
  vendor/golang.org/x/crypto/cast5/cast5.go
  vendor/golang.org/x/crypto/openpgp/armor/armor.go
  vendor/golang.org/x/crypto/openpgp/armor/encode.go
  vendor/golang.org/x/crypto/openpgp/canonical_text.go
  vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go
  vendor/golang.org/x/crypto/openpgp/errors/errors.go
  vendor/golang.org/x/crypto/openpgp/keys.go
  vendor/golang.org/x/crypto/openpgp/packet/compressed.go
  vendor/golang.org/x/crypto/openpgp/packet/config.go
  vendor/golang.org/x/crypto/openpgp/packet/encrypted_key.go
  vendor/golang.org/x/crypto/openpgp/packet/literal.go
  vendor/golang.org/x/crypto/openpgp/packet/ocfb.go
  vendor/golang.org/x/crypto/openpgp/packet/one_pass_signature.go
  vendor/golang.org/x/crypto/openpgp/packet/opaque.go
  vendor/golang.org/x/crypto/openpgp/packet/packet.go
  vendor/golang.org/x/crypto/openpgp/packet/private_key.go
  vendor/golang.org/x/crypto/openpgp/packet/public_key.go
  vendor/golang.org/x/crypto/openpgp/packet/public_key_v3.go
  vendor/golang.org/x/crypto/openpgp/packet/reader.go
  vendor/golang.org/x/crypto/openpgp/packet/signature.go
  vendor/golang.org/x/crypto/openpgp/packet/signature_v3.go
  vendor/golang.org/x/crypto/openpgp/packet/symmetric_key_encrypted.go
  vendor/golang.org/x/crypto/openpgp/packet/symmetrically_encrypted.go
  vendor/golang.org/x/crypto/openpgp/packet/userattribute.go
  vendor/golang.org/x/crypto/openpgp/packet/userid.go
  vendor/golang.org/x/crypto/openpgp/read.go
  vendor/golang.org/x/crypto/openpgp/s2k/s2k.go
  vendor/golang.org/x/crypto/openpgp/write.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#24 Cleanup format strings by using custom types.
  pkg/signing/formats/format.go
  pkg/signing/formats/tekton.go
  pkg/signing/signing.go
  pkg/signing/signing_test.go
  pkg/signing/storage/storage.go
  pkg/signing/storage/tekton/tekton.go
Labels: approved, lgtm, size/S

#25 Update tektoncd/pipeline to 0.14.2.
  cmd/controller/main.go
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/default.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/feature_flags.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/store.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/conversion_error.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/resource_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/doc.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/reconciler.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/timeout_handler.go
  vendor/knative.dev/caching/LICENSE
  vendor/knative.dev/caching/pkg/apis/caching/register.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/doc.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/image_defaults.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/image_types.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/image_validation.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/register.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/doc.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/scheme/doc.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/caching_client.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/doc.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/generated_expansion.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/image.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#23 Add boilerplate for e2e tests.
  go.mod
  test/clients.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e_test.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/openzipkin/zipkin-go/LICENSE
  vendor/github.com/openzipkin/zipkin-go/model/annotation.go
  vendor/github.com/openzipkin/zipkin-go/model/doc.go
  vendor/github.com/openzipkin/zipkin-go/model/endpoint.go
  vendor/github.com/openzipkin/zipkin-go/model/kind.go
  vendor/github.com/openzipkin/zipkin-go/model/span.go
  vendor/github.com/openzipkin/zipkin-go/model/span_id.go
  vendor/github.com/openzipkin/zipkin-go/model/traceid.go
  vendor/github.com/tektoncd/pipeline/pkg/names/generate.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/exec.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/funcs.go
  vendor/k8s.io/client-go/util/jsonpath/doc.go
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/k8s.io/client-go/util/jsonpath/node.go
  vendor/k8s.io/client-go/util/jsonpath/parser.go
  vendor/knative.dev/pkg/test/OWNERS
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/cleanup.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/crd.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/test/monitoring/doc.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/test-reconciler-codegen.sh
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#26 Small refactor of storage backend interfaces.
  pkg/signing/signing.go
  pkg/signing/signing_test.go
  pkg/signing/storage/storage.go
  pkg/signing/storage/tekton/tekton.go
  pkg/signing/storage/tekton/tekton_test.go
Labels: approved, lgtm, size/S

#28 Add an e2e test to check that TaskRuns get signed.
  pkg/signing/storage/tekton/tekton.go
  test/clients.go
  test/e2e_test.go
Labels: approved, lgtm, size/L

#30 Some documentation updates.
  DEVELOPMENT.md
  README.md
Labels: approved, lgtm, size/L

#31 Readme documentations updates and additions
  README.md
Labels: approved, lgtm, size/S

#21 Actually sign payloads!
  cmd/controller/main.go
  config/100-deployment.yaml
  go.mod
  go.sum
  pkg/signing/signing.go
  pkg/signing/signing_test.go
  pkg/signing/storage/storage.go
  pkg/signing/storage/tekton/tekton.go
  pkg/signing/storage/tekton/tekton_test.go
  test/README.md
  test/clients.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e_test.go
  test/testdata/README.md
  test/testdata/pgp.passphrase
  test/testdata/pgp.private-key
  test/testdata/pgp.public-key
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/errwrap/go.mod
  vendor/github.com/hashicorp/go-multierror/.travis.yml
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/Makefile
  vendor/github.com/hashicorp/go-multierror/README.md
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/go.mod
  vendor/github.com/hashicorp/go-multierror/go.sum
  vendor/github.com/hashicorp/go-multierror/group.go
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
  vendor/github.com/hashicorp/go-multierror/sort.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#29 More config store improvements.
  pkg/config/store.go
  pkg/config/store_test.go
  pkg/signing/signing.go
Labels: approved, lgtm, size/L

#32 fix format of note line.
  README.md
Labels: approved, lgtm, size/XS
