Repository tektoncd/chains, pull requests merged in 2020-08, with the labels that each got.

#34 Use base64 decode long option for different Unixes
  README.md
Labels: approved, lgtm, size/XS

#36 Rename the annotations to store signatures under.
  README.md
  pkg/signing/storage/tekton/tekton.go
  pkg/signing/storage/tekton/tekton_test.go
  test/e2e_test.go
Labels: approved, lgtm, size/S

#38 Change the format/storage model a bit to simplify usage.
  pkg/config/store.go
  pkg/config/store_test.go
Labels: approved, lgtm, size/M

#39 Hook up storage configs.
  cmd/controller/main.go
  config/100-deployment.yaml
  pkg/artifacts/signable.go
  pkg/config/store.go
  pkg/config/store_test.go
  pkg/signing/signing.go
  pkg/signing/signing_test.go
Labels: approved, lgtm, size/L

#40 Hook up the format config.
  pkg/artifacts/signable.go
  pkg/signing/signing.go
  pkg/signing/signing_test.go
Labels: approved, lgtm, size/M

#43 Add a "Key" method to the signable interface.
  README.md
  pkg/artifacts/signable.go
  pkg/signing/signing.go
  pkg/signing/signing_test.go
  pkg/signing/storage/storage.go
  pkg/signing/storage/tekton/tekton.go
  test/e2e_test.go
Labels: approved, lgtm, size/M

#44 Adding a simple taskrun example.
  README.md
  examples/task-output-image.yaml
Labels: approved, lgtm, size/M

#41 Document chains-config config map.
  README.md
Labels: approved, lgtm, size/XS

#45 OCI signing.
  go.mod
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
  pkg/config/store.go
  pkg/config/store_test.go
  pkg/signing/formats/format.go
  pkg/signing/formats/simple.go
  pkg/signing/formats/simple_test.go
  pkg/signing/signing.go
  pkg/signing/signing_test.go
  pkg/signing/storage/storage_test.go
  test/e2e_test.go
  vendor/github.com/google/go-containerregistry/LICENSE
  vendor/github.com/google/go-containerregistry/pkg/name/README.md
  vendor/github.com/google/go-containerregistry/pkg/name/check.go
  vendor/github.com/google/go-containerregistry/pkg/name/digest.go
  vendor/github.com/google/go-containerregistry/pkg/name/doc.go
  vendor/github.com/google/go-containerregistry/pkg/name/errors.go
  vendor/github.com/google/go-containerregistry/pkg/name/options.go
  vendor/github.com/google/go-containerregistry/pkg/name/ref.go
  vendor/github.com/google/go-containerregistry/pkg/name/registry.go
  vendor/github.com/google/go-containerregistry/pkg/name/repository.go
  vendor/github.com/google/go-containerregistry/pkg/name/tag.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#48 Test against nightly instead of latest.
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#47 Add an e2e test for OCI images.
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
  test/e2e-tests.sh
  test/e2e_test.go
  test/test_utils.go
Labels: approved, lgtm, size/M

#46 Also sign images from Task results.
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
Labels: approved, lgtm, size/M
