Repository tektoncd/chains, pull requests merged in 2021-09, with the labels that each got.

#219 Switch the linter from golint to revive.
  .golang-ci.yaml
Labels: size/XS, lgtm, approved

#220 Fix some bugs in uploading attestations
  pkg/chains/signing.go
  pkg/chains/storage/oci/oci.go
  pkg/config/options.go
Labels: size/M, lgtm, approved

#223 fix incorrect cd
  DEVELOPMENT.md
Labels: size/XS, lgtm, approved, ok-to-test

#224 Small typo in provenance spec
  PROVENANCE_SPEC.md
Labels: size/XS, lgtm, approved

#192 Add Chains API service
  cmd/server/server.go
  config/100-deployment.yaml
  go.mod
  hack/proto/Dockerfile
  hack/proto/generate-proto.sh
  pkg/config/config.go
  pkg/config/store_test.go
  pkg/server/entry.go
  pkg/server/entry_test.go
  pkg/server/server.go
  proto/chains.pb.go
  proto/chains.pb.gw.go
  proto/chains.proto
  test/e2e_test.go
  test/test_utils.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#227 Fix bug in storing attestations in OCI registry
  pkg/chains/storage/oci/oci.go
  test/e2e_test.go
Labels: lgtm, size/S, approved

#228 Add minor chains tutorial enhancements
  docs/tutorial.md
Labels: size/XS, lgtm, approved

#229 Check task status params to create materials for provenance
  pkg/chains/formats/provenance/provenance.go
Labels: lgtm, size/S, approved

#231 e2e test: verify OCI image and attestation with cosign insecure flag
  test/clients.go
  test/e2e_test.go
  test/kaniko.go
  test/test_utils.go
Labels: size/L, lgtm, approved

#232 Simplify looking up the RekorAnnotation, add Unit Test for HandleRetry failure
  pkg/chains/rekor.go
  pkg/chains/signing_test.go
Labels: size/M, lgtm, approved, ok-to-test

#230 Fix another bug in materials and add integration test
  pkg/chains/formats/provenance/provenance.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e_test.go
  test/test_utils.go
Labels: size/L, lgtm, approved

#233 Fix bug in transparency log uploads
  pkg/config/config.go
  pkg/config/store_test.go
Labels: size/M, lgtm, approved

#235 Fix _type field in in-toto provenance generation
  pkg/chains/formats/provenance/provenance.go
Labels: size/XS, lgtm, approved

#238 Add tutorial for generating signed provenance
  README.md
  docs/authentication.md
  docs/tutorials/getting-started-tutorial.md
  docs/tutorials/signed-provenance-tutorial.md
Labels: size/L, lgtm, approved

#240 Update release README
  release/README.md
Labels: size/XS, lgtm, approved

#243 Switch DSSE provider to go-securesystemslib
  go.mod
  go.sum
  pkg/chains/signing/wrap.go
  test/e2e_test.go
  test/examples_test.go
  vendor/github.com/secure-systems-lab/go-securesystemslib/LICENSE
  vendor/github.com/secure-systems-lab/go-securesystemslib/dsse/sign.go
  vendor/github.com/secure-systems-lab/go-securesystemslib/dsse/verify.go
  vendor/github.com/sigstore/sigstore/pkg/signature/dsse/dsse.go
  vendor/modules.txt
Labels: lgtm, size/S, approved, ok-to-test

#242 Make sure released images in mirrors are signed
  release/publish.yaml
Labels: size/XS, lgtm, approved
