Repository tektoncd/chains, pull requests merged in 2021-05, with the labels that each got.

#78 Add priyawadhwa@ as an approver
  OWNERS
Labels: approved, lgtm, size/XS

#77 Run tekton-chains-controller under it's own service account
  config/100-deployment.yaml
  config/100-rolebinding.yaml
  config/config-logging.yaml
  pkg/chains/storage/oci/oci.go
  test/clients.go
  test/e2e-common.sh
  test/e2e_test.go
  test/test_utils.go
Labels: approved, lgtm, size/L

#80 e2e testing: port forward registry for external access
  test/clients.go
  test/e2e_test.go
Labels: approved, lgtm, size/L

#94 Add kaniko Task and TaskRun example
  examples/kaniko/kaniko.yaml
  examples/kaniko/taskrun.yaml
Labels: approved, lgtm, size/M

#92 Provide example on PKCS8 PEM format conversion
  README.md
Labels: approved, lgtm, size/XS

#95 fix namespace in authentication doc
  docs/authentication.md
Labels: approved, lgtm, size/XS

#89 in-toto attestations (ITE-6) as a formatter.
  INTOTO.md
  README.md
  go.mod
  go.sum
  pkg/chains/formats/format.go
  pkg/chains/formats/intotoite6/intotoite6.go
  pkg/chains/formats/intotoite6/intotoite6_test.go
  pkg/chains/formats/simple/simple.go
  pkg/chains/formats/simple/simple_test.go
  pkg/chains/formats/tekton/tekton.go
  pkg/chains/formats/tekton/tekton_test.go
  pkg/chains/signing.go
  pkg/chains/storage/oci/oci.go
  pkg/config/store.go
  vendor/github.com/in-toto/in-toto-golang/LICENSE
  vendor/github.com/in-toto/in-toto-golang/in_toto/canonicaljson.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/hashlib.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/keylib.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/model.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/rulelib.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/runlib.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/util.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/verifylib.go
  vendor/github.com/shibumi/go-pathspec/.gitignore
  vendor/github.com/shibumi/go-pathspec/GO-LICENSE
  vendor/github.com/shibumi/go-pathspec/LICENSE
  vendor/github.com/shibumi/go-pathspec/README.md
  vendor/github.com/shibumi/go-pathspec/gitignore.go
  vendor/github.com/shibumi/go-pathspec/go.mod
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/XXL

#101 Minor ite-6 fixes.
  INTOTO.md
  pkg/chains/formats/intotoite6/intotoite6.go
  pkg/chains/formats/intotoite6/intotoite6_test.go
  pkg/chains/signing.go
  pkg/config/store.go
  pkg/config/store_test.go
Labels: approved, lgtm, size/L

#103 Add script for generating an ecdsa keypair
  .gitignore
  README.md
  gen-keys.sh
Labels: approved, lgtm, size/M

#107 Some intoto refactoring
  go.mod
  pkg/chains/formats/intotoite6/intotoite6.go
  pkg/chains/signing.go
Labels: approved, lgtm, size/L
