Repository tektoncd/chains, pull requests merged in 2021-12, with the labels that each got.

#290 Fix flag dashes
  docs/tutorials/getting-started-tutorial.md
Labels: size/XS, lgtm, approved, ok-to-test

#295 Add loosebazooka to chains approvers
  OWNERS
Labels: size/XS, lgtm, approved

#292 Deprecate the `tekton-provenance` predicate format
  PROVENANCE_SPEC.md
  docs/config.md
  docs/deprecations.md
  docs/intoto.md
  docs/tutorials/signed-provenance-tutorial.md
  pkg/chains/formats/provenance/provenance.go
  pkg/chains/signing.go
  pkg/chains/storage/oci/oci_test.go
  test/e2e_test.go
Labels: size/L, lgtm, approved

#298 Fix bug in uploading signatures to OCI
  pkg/chains/storage/oci/oci.go
Labels: size/XS, lgtm, approved

#299 Update release README
  release/README.md
Labels: size/XS, lgtm, approved

#300 Add extension to gcs storage payload
  pkg/chains/formats/format.go
  pkg/chains/signing.go
  pkg/chains/storage/gcs/gcs.go
  pkg/chains/storage/gcs/gcs_test.go
  pkg/chains/storage/oci/oci.go
  pkg/config/options.go
Labels: size/L, lgtm, approved

#304 go back to using payload with no extension
  pkg/chains/storage/gcs/gcs.go
  pkg/chains/storage/gcs/gcs_test.go
Labels: size/M, lgtm, approved

#302 added multi-backend support
  docs/config.md
  docs/tutorials/getting-started-tutorial.md
  pkg/artifacts/signable.go
  pkg/chains/signing.go
  pkg/chains/signing_test.go
  pkg/chains/storage/storage.go
  pkg/chains/storage/storage_test.go
  pkg/chains/verifier.go
  pkg/config/config.go
  pkg/config/store_test.go
  test/e2e_test.go
  test/test_utils.go
Labels: size/L, lgtm, approved, ok-to-test

#307 Make SLSA provenance v0.2 invocation.parameters compliant with spec
  pkg/chains/formats/intotoite6/intotoite6.go
  pkg/chains/formats/intotoite6/intotoite6_test.go
  pkg/chains/formats/intotoite6/provenance_test.go
  pkg/chains/provenance/provenance.go
  test/testdata/intoto/task-output-image.json
Labels: size/M, lgtm, approved, ok-to-test
