Repository tektoncd/chains, pull requests merged in 2021-08, with the labels that each got.

#176 Configure release to include materials section in provenance
  release/publish.yaml
  release/release-pipeline.yaml
Labels: approved, lgtm, size/XS

#178 Fixed the missing go.mod
  go.mod
  vendor/modules.txt
Labels: size/XS, lgtm, approved, ok-to-test

#177 Explicitly pass in URL for provenance materials
  release/publish.yaml
  release/release-pipeline.yaml
Labels: size/XS, lgtm, approved

#185 Add chains finalizer to taskruns.
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
Labels: lgtm, size/S, approved

#188 Increase timeout on golangci-lint to 10m
  test/presubmit-tests.sh
Labels: size/XS, lgtm, approved

#182 add missing recipe_uri in JSON
  PROVENANCE_SPEC.md
Labels: size/XS, lgtm, approved, ok-to-test

#189 Implemented license header check
  config/100-deployment.yaml
  config/100-rolebinding.yaml
  examples/kaniko/gcp/kaniko.yaml
  examples/kaniko/gcp/taskrun.yaml
  examples/kaniko/kaniko.yaml
  examples/kaniko/taskrun.yaml
  examples/releases/v0.3.0-build-chains-taskrun.yaml
  examples/taskruns/task-output-image.yaml
  go.mod
  go.sum
  hack/tools.go
  pkg/patch/patch.go
  pkg/patch/patch_test.go
  release/publish.yaml
  release/release-pipeline.yaml
  test/presubmit-tests.sh
  vendor/github.com/bmatcuk/doublestar/v4/.gitignore
  vendor/github.com/bmatcuk/doublestar/v4/.travis.yml
  vendor/github.com/bmatcuk/doublestar/v4/LICENSE
  vendor/github.com/bmatcuk/doublestar/v4/README.md
  vendor/github.com/bmatcuk/doublestar/v4/UPGRADING.md
  vendor/github.com/bmatcuk/doublestar/v4/doublestar.go
  vendor/github.com/bmatcuk/doublestar/v4/glob.go
  vendor/github.com/bmatcuk/doublestar/v4/globwalk.go
  vendor/github.com/bmatcuk/doublestar/v4/go.mod
  vendor/github.com/bmatcuk/doublestar/v4/match.go
  vendor/github.com/bmatcuk/doublestar/v4/utils.go
  vendor/github.com/bmatcuk/doublestar/v4/validate.go
  vendor/github.com/google/addlicense/.gitignore
  vendor/github.com/google/addlicense/.golangci.yaml
  vendor/github.com/google/addlicense/.goreleaser.yaml
  vendor/github.com/google/addlicense/CONTRIBUTING.md
  vendor/github.com/google/addlicense/Dockerfile
  vendor/github.com/google/addlicense/LICENSE
  vendor/github.com/google/addlicense/README.md
  vendor/github.com/google/addlicense/go.mod
  vendor/github.com/google/addlicense/go.sum
  vendor/github.com/google/addlicense/main.go
  vendor/github.com/google/addlicense/tmpl.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, ok-to-test

#175 Add manual option for uploads to transparency log
  docs/config.md
  pkg/chains/rekor.go
  pkg/chains/rekor_test.go
  pkg/chains/signing.go
  pkg/chains/signing_test.go
  pkg/config/config.go
  pkg/config/store_test.go
  release/publish.yaml
  release/release-pipeline.yaml
  test/e2e_test.go
Labels: size/L, lgtm, approved

#193 Add label dependabot PRs ok-to-test
  .github/dependabot.yml
Labels: size/XS, lgtm, approved, ok-to-test

#197 Removed the link to broken README.md within test
  test/README.md
Labels: size/XS, lgtm, approved, ok-to-test

#200 Doc-removed gen x509 Keypair ,fixed cosign gen
  docs/signing.md
Labels: size/XS, lgtm, approved, ok-to-test

#202 Only upload to the tlog once!
  pkg/chains/rekor.go
  pkg/chains/rekor_test.go
Labels: lgtm, size/S, approved

#207 Try to sign a TaskRun a maximum of 3 times
  pkg/chains/annotations.go
  pkg/chains/annotations_test.go
  pkg/chains/signing.go
  pkg/chains/signing_test.go
  pkg/chains/storage/oci/oci.go
  pkg/reconciler/taskrun/taskrun.go
  test/e2e_test.go
  test/test_utils.go
Labels: size/L, lgtm, approved
