Repository tektoncd/chains, pull requests merged in 2021-06, with the labels that each got.

#104 README updates
  README.md
  docs/authentication.md
  docs/config.md
  docs/intoto.md
  docs/signing.md
  docs/tutorial.md
  pkg/chains/storage/oci/oci.go
  tekton_chains-color.png
Labels: approved, lgtm, size/XL

#112 Update README to include details about Slack and the WG meeting
  README.md
Labels: approved, lgtm, size/XS

#114 Update cosign key generation in docs
  docs/signing.md
  docs/tutorial.md
  gen-keys.sh
Labels: approved, lgtm, size/M

#115 Fix tutorial
  README.md
  docs/tutorial.md
Labels: approved, lgtm, size/XS

#116 Warn user if config has incorrect values
  pkg/chains/signing.go
  pkg/config/store.go
  pkg/config/store_test.go
Labels: approved, lgtm, size/M

#118 Add GCP specific kaniko task
  examples/kaniko/gcp/kaniko.yaml
  examples/kaniko/gcp/taskrun.yaml
Labels: approved, lgtm, size/M

#122 Update text ʕ•́ᴥ•̀ʔ
  docs/tutorial.md
Labels: approved, lgtm, size/XS

#121 Transparency log uploads in chains!
  .gitignore
  docs/config.md
  go.mod
  go.sum
  pkg/chains/rekor.go
  pkg/chains/signing.go
  pkg/chains/signing/x509/testdata/README.md
  pkg/chains/signing/x509/testdata/x509.pem
  pkg/chains/signing_test.go
  pkg/config/store.go
  pkg/config/store_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#109 Support the ITE-5 signing spec
  go.mod
  go.sum
  pkg/chains/formats/format.go
  pkg/chains/formats/intotoite6/intotoite6.go
  pkg/chains/formats/simple/simple.go
  pkg/chains/formats/tekton/tekton.go
  pkg/chains/signing.go
  pkg/chains/signing/wrap.go
  pkg/chains/signing/x509/x509.go
  pkg/config/store.go
  test/e2e_test.go
  test/examples_test.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/model.go
  vendor/github.com/in-toto/in-toto-golang/pkg/ssl/sign.go
  vendor/github.com/in-toto/in-toto-golang/pkg/ssl/verify.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#123 Add SPIRE verification to chains
  pkg/chains/formats/tekton/tekton.go
  pkg/chains/signing.go
  pkg/chains/spire/spire.go
  pkg/chains/spire/spire_test.go
  pkg/config/store.go
Labels: approved, lgtm, size/L

#126 Fix docdb behavior on retries
  pkg/chains/storage/docdb/docdb.go
Labels: approved, lgtm, size/XS
