Repository tektoncd/chains, pull requests merged in 2021-11, with the labels that each got.

#272 Capture step information in`recipe.arguments` for in-toto/slsa Provenance
  pkg/chains/formats/intotoite6/intotoite6.go
  pkg/chains/formats/intotoite6/intotoite6_test.go
  pkg/chains/formats/provenance/provenance.go
  pkg/chains/formats/provenance/provenance_test.go
  test/examples_test.go
  test/testdata/intoto/task-output-image.json
Labels: size/L, lgtm, approved, ok-to-test

#281 Fix URL for entry within annotation
  pkg/chains/signing.go
Labels: size/XS, lgtm, approved, ok-to-test

#285 Add front matter to docs
  README.md
  docs/authentication.md
  docs/config.md
  docs/experimental.md
  docs/intoto.md
  docs/signing.md
  docs/tutorials/getting-started-tutorial.md
  docs/tutorials/signed-provenance-tutorial.md
Labels: size/L, lgtm, kind/documentation, approved

#286 Fix the front matter for the experimental docs
  docs/experimental.md
Labels: size/XS, lgtm, approved
