Repository tektoncd/chains, pull requests merged in 2021-07, with the labels that each got.

#129 Add support for hinting multiple images as results
  docs/config.md
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
Labels: approved, lgtm, size/M

#130 Make the configmap watcher a bit more robust.
  pkg/config/store.go
Labels: approved, lgtm, size/M

#131 Plumb a context through into the config map watcher.
  cmd/controller/main.go
  pkg/config/store.go
  pkg/config/store_test.go
Labels: approved, lgtm, size/S

#134 Don't require prefix when image hinting
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
Labels: approved, lgtm, size/XS

#138 Structure the reconciler in a more consistent fashion.
  cmd/controller/main.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#136 Add some details to the roadmap
  ROADMAP.md
Labels: approved, lgtm, size/XS

#137 Fix flaky unit test
  pkg/artifacts/signable_test.go
Labels: approved, lgtm, size/XS

#141 Switch to google's cmp
  pkg/artifacts/signable_test.go
Labels: approved, kind/cleanup, lgtm, size/S

#140 Enable HA
  cmd/controller/main.go
  config/100-rolebinding.yaml
Labels: approved, lgtm, size/M

#143 Switch the tests from pgp to x509 signing.
  test/clients.go
  test/e2e_test.go
  test/test_utils.go
  test/testdata/pgp.passphrase
  test/testdata/pgp.private-key
  test/testdata/pgp.public-key
Labels: approved, lgtm, size/M

#144 Remove PGP signing!
  README.md
  config/100-deployment.yaml
  docs/config.md
  docs/signing.md
  docs/tutorial.md
  go.mod
  go.sum
  pkg/chains/signing.go
  pkg/chains/signing/iface.go
  pkg/chains/signing/pgp/pgp.go
  pkg/chains/signing/pgp/pgp_test.go
  pkg/chains/signing/pgp/testdata/README.md
  pkg/chains/signing/pgp/testdata/pgp.passphrase
  pkg/chains/signing/pgp/testdata/pgp.private-key
  pkg/chains/signing/pgp/testdata/pgp.public-key
  pkg/chains/signing/x509/x509.go
  pkg/chains/signing_test.go
  pkg/config/store.go
  pkg/config/store_test.go
  test/testdata/README.md
  vendor/modules.txt
Labels: approved, lgtm, size/L

#128 Container native provenance predicate
  PROVENANCE_SPEC.md
  go.mod
  images/provenance-diagram.png
  pkg/chains/formats/format.go
  pkg/chains/formats/provenance/provenance.go
  pkg/chains/formats/provenance/provenance_test.go
  pkg/chains/provenance/provenance.go
  pkg/chains/rekor.go
  pkg/chains/signing.go
  pkg/chains/signing_test.go
  pkg/config/store.go
  vendor/github.com/sigstore/rekor/pkg/types/intoto/intoto.go
  vendor/github.com/sigstore/rekor/pkg/types/intoto/intoto_schema.json
  vendor/github.com/sigstore/rekor/pkg/types/intoto/v0.0.1/entry.go
  vendor/github.com/sigstore/rekor/pkg/types/intoto/v0.0.1/intoto_v0_0_1_schema.json
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#149 Use controller.HandleAll
  pkg/reconciler/taskrun/controller.go
Labels: approved, kind/cleanup, lgtm, size/XS

#151 Add myself to approvers.
  OWNERS
Labels: approved, lgtm, size/XS

#153 Add IMAGES results type, to be used for releases
  docs/config.md
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
Labels: approved, lgtm, size/M

#154 Pass in OIDC issuer and client to fulcio
  pkg/chains/signing/x509/x509.go
Labels: approved, lgtm, size/XS

#160 Fix format directive.
  pkg/chains/signing.go
Labels: approved, kind/cleanup, lgtm, size/XS

#159 Drop the config-logging volume mount.
  config/100-deployment.yaml
Labels: approved, kind/cleanup, lgtm, size/XS

#162 Plumb `kubernetes.Interface` through storage backends.
  go.mod
  go.sum
  pkg/chains/signing.go
  pkg/chains/signing_test.go
  pkg/chains/storage/oci/oci.go
  pkg/chains/storage/storage.go
  pkg/chains/storage/storage_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun_test.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/modules.txt
Labels: approved, kind/cleanup, lgtm, size/L

#163 Change the ServiceAccount identity used for OCI storage backend.
  pkg/chains/storage/oci/oci.go
Labels: approved, lgtm, size/XS

#158 Resolve some nil pointer exceptions
  pkg/chains/formats/provenance/provenance.go
  pkg/chains/formats/provenance/provenance_test.go
Labels: approved, lgtm, size/S

#155 Save all images built during release process as a result
  pkg/chains/provenance/provenance.go
  release/publish.yaml
Labels: approved, lgtm, size/XS

#165 Check in public key for verifying Chains releases
  tekton.pub
Labels: approved, lgtm, size/XS

#168 Add a taskrun for building chains in tekton
  examples/releases/v0.3.0-build-chains-taskrun.yaml
Labels: approved, lgtm, size/M

#164 Update docs for v0.3.0 release
  README.md
  docs/authentication.md
  docs/config.md
  docs/experimental.md
  docs/intoto.md
  docs/signing.md
Labels: approved, lgtm, size/L

#169 Store cert/chain when wrapping payloads
  DEVELOPMENT.md
  pkg/chains/signing/wrap.go
  pkg/chains/signing/x509/x509.go
  test/clients.go
  test/e2e_test.go
Labels: approved, lgtm, size/L

#170 Fix auth bug for pushing images in release pipeline
  release/publish.yaml
Labels: approved, lgtm, size/XS

#171 Bump cosign to 1.0!
  go.mod
  go.sum
  pkg/chains/signing/x509/x509.go
  pkg/chains/storage/oci/oci.go
  vendor/cloud.google.com/go/CHANGES.md
  vendor/cloud.google.com/go/README.md
  vendor/cloud.google.com/go/container/apiv1/doc.go
  vendor/cloud.google.com/go/go.mod
  vendor/cloud.google.com/go/go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/cloud.google.com/go/kms/apiv1/doc.go
  vendor/cloud.google.com/go/monitoring/apiv3/doc.go
  vendor/cloud.google.com/go/trace/apiv2/doc.go
  vendor/github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcio.go
  vendor/github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcio.pem
  vendor/github.com/sigstore/cosign/pkg/cosign/fetch.go
  vendor/github.com/sigstore/cosign/pkg/cosign/remote/index.go
  vendor/github.com/sigstore/cosign/pkg/cosign/remote/remote.go
  vendor/github.com/sigstore/cosign/pkg/cosign/verifiers.go
  vendor/github.com/sigstore/cosign/pkg/cosign/verify.go
  vendor/github.com/sigstore/fulcio/pkg/client/client.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#172 Fix GOPATH bug in TaskRun, image should now match the released image
  examples/releases/v0.3.0-build-chains-taskrun.yaml
Labels: approved, lgtm, size/M
