Repository tektoncd/chains, pull requests merged in 2022-02, with the labels that each got.

#361 Pass in authentication when getting remote image
  pkg/chains/storage/oci/oci.go
Labels: size/XS, lgtm, approved

#360 Change default Fulcio URL to match cosign's
  pkg/config/config.go
  pkg/config/store_test.go
Labels: size/XS, lgtm, approved, ok-to-test

#365 Fix default fulcio addr in docs
  docs/config.md
Labels: size/XS, lgtm, approved

#373 Bump sigstore/sigstore dep and explicitly import KMSes
  go.mod
  go.sum
  pkg/chains/signing/kms/kms.go
  vendor/cloud.google.com/go/kms/apiv1/doc.go
  vendor/cloud.google.com/go/kms/apiv1/ekm_client.go
  vendor/cloud.google.com/go/kms/apiv1/gapic_metadata.json
  vendor/cloud.google.com/go/kms/apiv1/key_management_client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/v7.1/keyvault/dataplane_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/containerregistry/runtime/2019-08-15-preview/containerregistry/dataplane_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/rest/build.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/rest/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/service/dynamodb/api.go
  vendor/github.com/sigstore/sigstore/pkg/oauthflow/pkce.go
  vendor/github.com/sigstore/sigstore/pkg/signature/kms/aws/client.go
  vendor/github.com/sigstore/sigstore/pkg/signature/kms/azure/client.go
  vendor/github.com/sigstore/sigstore/pkg/signature/kms/gcp/client.go
  vendor/github.com/sigstore/sigstore/pkg/signature/kms/hashivault/client.go
  vendor/github.com/sigstore/sigstore/pkg/signature/kms/hashivault/signer.go
  vendor/github.com/sigstore/sigstore/pkg/signature/kms/kms.go
  vendor/github.com/sigstore/sigstore/pkg/signature/options.go
  vendor/github.com/sigstore/sigstore/pkg/signature/options/keyversion.go
  vendor/github.com/sigstore/sigstore/pkg/signature/options/noop.go
  vendor/github.com/theupdateframework/go-tuf/README.md
  vendor/github.com/theupdateframework/go-tuf/client/delegations.go
  vendor/github.com/theupdateframework/go-tuf/internal/targets/hash_bins.go
  vendor/github.com/theupdateframework/go-tuf/pkg/keys/ed25519.go
  vendor/github.com/theupdateframework/go-tuf/pkg/targets/delegation.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#379 Add community tutorial subsection
  README.md
Labels: size/M, lgtm, approved, ok-to-test
