Repository tektoncd/chains, pull requests merged in 2022-03, with the labels that each got.

#380 Introduce kind based e2e tests.
  .github/workflows/kind-e2e.yaml
Labels: size/L, lgtm, approved, ok-to-test

#387 Fix the inconsistent labels on chains resource
  config/100-deployment.yaml
  config/100-rolebinding.yaml
  config/config-info.yaml
  config/config-logging.yaml
Labels: size/M, lgtm, approved

#388 Revert default fulcio URL to fulcio.sigstore.dev
  pkg/config/config.go
  pkg/config/store_test.go
Labels: size/XS, lgtm, approved

#394 Remove usage of context.TODO
  pkg/chains/annotations.go
  pkg/chains/annotations_test.go
  pkg/chains/signing.go
  pkg/chains/signing/kms/kms.go
  pkg/chains/signing/x509/x509.go
  pkg/chains/signing/x509/x509_test.go
  pkg/chains/signing_test.go
  pkg/chains/storage/docdb/docdb.go
  pkg/chains/storage/docdb/docdb_test.go
  pkg/chains/storage/gcs/gcs.go
  pkg/chains/storage/gcs/gcs_test.go
  pkg/chains/storage/oci/oci.go
  pkg/chains/storage/oci/oci_test.go
  pkg/chains/storage/storage.go
  pkg/chains/storage/storage_test.go
  pkg/chains/storage/tekton/tekton.go
  pkg/chains/storage/tekton/tekton_test.go
  pkg/chains/verifier.go
  test/test_utils.go
Labels: size/L, lgtm, approved

#403 Do not fail OCI upload when no subjects
  pkg/chains/storage/oci/oci.go
  pkg/chains/storage/oci/oci_test.go
Labels: lgtm, size/S, approved, ok-to-test

#409 Use sigstore/scaffolding github actions now that it's out there.
  .github/workflows/kind-e2e.yaml
Labels: size/M, lgtm, approved
