Repository tektoncd/chains, pull requests merged in 2022-10, with the labels that each got.

#580 Add the OpenSSF badge to the main README
  README.md
Labels: size/XS, kind/documentation

#578 Pin e2e tests to Pipelines v0.40.0
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved

#588 Pin kind e2e tests to pipelines 0.40.0.
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#581 docs: fix verify-attestation cmd
  docs/tutorials/signed-provenance-tutorial.md
Labels: size/XS, lgtm, approved, ok-to-test

#582 fix: pubusub to pubsub in storage backend support of experimental features
  docs/experimental.md
Labels: size/XS, lgtm, approved, ok-to-test

#573 Document PipelineRun attestations
  docs/config.md
  docs/experimental.md
  docs/intoto.md
Labels: size/L, lgtm, approved

#593 Add releases.md
  README.md
  releases.md
Labels: size/M, lgtm, approved

#575 chore: upgrade setup-ko to its latest version
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#579 allow reading the pull secret from the podTemplate
  docs/authentication.md
  pkg/chains/objects/objects.go
  pkg/chains/objects/objects_test.go
  pkg/chains/storage/oci/oci.go
Labels: size/L, lgtm, approved, ok-to-test

#594 Remove unsupported tekton-provenance storage in config
  pkg/config/config.go
Labels: size/XS, lgtm, approved, kind/misc

#589 Full access to image url and digest in StorageOpts
  pkg/artifacts/signable.go
  pkg/chains/signing.go
  pkg/chains/storage/docdb/docdb.go
  pkg/chains/storage/docdb/docdb_test.go
  pkg/chains/storage/gcs/gcs.go
  pkg/chains/storage/gcs/gcs_test.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/chains/storage/tekton/tekton.go
  pkg/chains/storage/tekton/tekton_test.go
  pkg/config/options.go
  test/test_utils.go
Labels: size/L, lgtm, approved

#598 Adding pipelinerun attestations to e2e tests
  examples/pipelineruns/pipeline-output-image.yaml
  pkg/chains/annotations_test.go
  pkg/chains/objects/objects.go
  pkg/chains/signing_test.go
  pkg/chains/storage/tekton/tekton_test.go
  pkg/test/tekton/tekton.go
  test/clients.go
  test/e2e_test.go
  test/examples_test.go
  test/kaniko.go
  test/test_utils.go
  test/testdata/intoto/pipeline-output-image.json
  test/testdata/intoto/task-output-image.json
Labels: lgtm, size/XXL, approved, ok-to-test

#590 Grafeas storage for PipelineRun-level provenance
  pkg/chains/formats/intotoite6/extract/extract.go
  pkg/chains/formats/intotoite6/extract/extract_test.go
  pkg/chains/formats/intotoite6/pipelinerun/pipelinerun.go
  pkg/chains/formats/intotoite6/taskrun/taskrun.go
  pkg/chains/objects/objects.go
  pkg/chains/signing.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/chains/storage/oci/oci.go
  pkg/chains/storage/tekton/tekton.go
  pkg/config/config.go
  test/test_utils.go
Labels: lgtm, size/XXL, approved

#600 Revert "Remove unsupported tekton-provenance storage in config (#594)(#590)"
  pkg/chains/formats/intotoite6/extract/extract.go
  pkg/chains/formats/intotoite6/extract/extract_test.go
  pkg/chains/formats/intotoite6/pipelinerun/pipelinerun.go
  pkg/chains/formats/intotoite6/taskrun/taskrun.go
  pkg/chains/objects/objects.go
  pkg/chains/signing.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/chains/storage/oci/oci.go
  pkg/chains/storage/tekton/tekton.go
  pkg/config/config.go
  test/test_utils.go
Labels: lgtm, size/XXL, approved

#601 Grafeas storage for PipelineRun-level provenance
  pkg/chains/formats/intotoite6/extract/extract.go
  pkg/chains/formats/intotoite6/extract/extract_test.go
  pkg/chains/formats/intotoite6/pipelinerun/pipelinerun.go
  pkg/chains/formats/intotoite6/taskrun/taskrun.go
  pkg/chains/objects/objects.go
  pkg/chains/signing.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/chains/storage/oci/oci.go
  pkg/chains/storage/tekton/tekton.go
  pkg/config/config.go
  test/test_utils.go
Labels: kind/feature, lgtm, size/XXL, approved
