Repository tektoncd/chains, pull requests merged in 2022-04, with the labels that each got.

#413 Adding Go linting
  .github/workflows/lint.yaml
  pkg/chains/formats/intotoite6/intotoite6.go
  pkg/chains/signing/wrap.go
  pkg/chains/signing/x509/x509_test.go
  pkg/chains/storage/docdb/docdb_test.go
  pkg/chains/storage/gcs/gcs_test.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/chains/storage/tekton/tekton.go
  pkg/config/config.go
  pkg/config/store.go
Labels: size/L, lgtm, approved, ok-to-test

#417 Remove unused funcs/vars reported by golangci-lint
  pkg/chains/formats/intotoite6/intotoite6.go
  pkg/chains/rekor.go
  pkg/chains/storage/tekton/tekton.go
Labels: lgtm, size/S, approved

#414 Add godoc documentation
  pkg/config/options.go
Labels: lgtm, size/S, approved

#422 Fix nightly builds
  release/kustomization.yaml
Labels: lgtm, size/S, approved, ok-to-test

#427 Fix flaky grafeas unit test
  pkg/chains/storage/grafeas/grafeas_test.go
Labels: lgtm, size/S, approved

#429 Update OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#430 Add docs for secrets based on existing credentials
  docs/authentication.md
Labels: size/M, lgtm, approved
