Repository tektoncd/chains, pull requests merged in 2022-11, with the labels that each got.

#610 Use cos_containerd image for e2e tests
  go.mod
  go.sum
  test/testdata/intoto/pipeline-output-image.json
  vendor/github.com/tektoncd/plumbing/.gitignore
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#607 Stop reconciliation on unrecoverable error
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: size/M, lgtm, approved

#599 Support structured results for PipelineRunObject
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
  pkg/chains/objects/objects.go
  pkg/chains/objects/objects_test.go
Labels: size/L, lgtm, approved

#611 Update README.md
  README.md
Labels: size/XS, lgtm, approved, ok-to-test

#619 Add lcarva, chuangw6 to global approvers.
  OWNERS
Labels: size/XS, lgtm, approved

#604 Add spiffe-csi driver support to authentication part
  docs/authentication.md
Labels: lgtm, size/S, approved, ok-to-test

#631 Convert times to UTC
  pkg/chains/formats/intotoite6/pipelinerun/pipelinerun.go
  pkg/chains/formats/intotoite6/pipelinerun/provenance_test.go
  pkg/chains/formats/intotoite6/taskrun/provenance_test.go
  pkg/chains/formats/intotoite6/taskrun/taskrun.go
Labels: size/M, lgtm, approved, ok-to-test

#554 Record `invocation.configSource` section in slsa provenance
  pkg/chains/formats/intotoite6/attest/attest.go
  pkg/chains/formats/intotoite6/intotoite6_test.go
  pkg/chains/formats/intotoite6/pipelinerun/pipelinerun.go
  pkg/chains/formats/intotoite6/pipelinerun/provenance_test.go
  pkg/chains/formats/intotoite6/taskrun/taskrun.go
  pkg/chains/formats/intotoite6/testdata/pipelinerun1.json
  pkg/chains/formats/intotoite6/testdata/taskrun1.json
  pkg/chains/formats/intotoite6/testdata/taskrun2.json
Labels: size/L, lgtm, approved
