Repository tektoncd/chains, pull requests merged in 2022-05, with the labels that each got.

#438 Disable unit test that requires GCP credentials
  pkg/chains/storage/storage_test.go
Labels: lgtm, size/S, approved

#437 Add todos in Grafeas storage
  pkg/chains/storage/grafeas/grafeas.go
Labels: size/XS, lgtm, approved

#439 Remove tekton-provenance format
  pkg/chains/formats/format.go
  pkg/chains/formats/provenance/provenance.go
  pkg/chains/formats/provenance/provenance_test.go
  pkg/chains/rekor.go
  pkg/chains/signing.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/oci/oci.go
  pkg/config/config.go
Labels: size/XL, lgtm, approved

#432 Change SCC from anyuid to nonroot
  README.md
Labels: size/XS, lgtm, approved

#446 Disable unit test for grafeas backend creation
  pkg/chains/storage/storage_test.go
Labels: lgtm, size/S, approved

#448 Remove fmt.Println calls from the code base
  pkg/chains/formats/intotoite6/buildconfig.go
  pkg/chains/storage/pubsub/pubsub.go
  pkg/chains/storage/pubsub/pubsub_test.go
Labels: size/XS, lgtm, approved, ok-to-test

#444 Allow TaskRun payloads other than IMAGE_URL
  pkg/chains/storage/tekton/tekton.go
Labels: lgtm, size/S, approved

#454 Bump version of rekor to v0.5.0
  go.mod
  go.sum
  vendor/github.com/PuerkitoBio/purell/.gitignore
  vendor/github.com/PuerkitoBio/purell/.travis.yml
  vendor/github.com/PuerkitoBio/purell/LICENSE
  vendor/github.com/PuerkitoBio/purell/README.md
  vendor/github.com/PuerkitoBio/purell/purell.go
  vendor/github.com/PuerkitoBio/urlesc/.travis.yml
  vendor/github.com/PuerkitoBio/urlesc/LICENSE
  vendor/github.com/PuerkitoBio/urlesc/README.md
  vendor/github.com/PuerkitoBio/urlesc/urlesc.go
  vendor/github.com/go-openapi/jsonreference/internal/normalize_url.go
  vendor/github.com/go-openapi/jsonreference/reference.go
  vendor/github.com/go-playground/validator/v10/README.md
  vendor/github.com/jedisct1/go-minisign/minisign.go
  vendor/github.com/sigstore/rekor/pkg/generated/models/log_entry.go
  vendor/github.com/sigstore/rekor/pkg/pki/minisign/minisign.go
  vendor/github.com/sigstore/rekor/pkg/pki/ssh/README.md
  vendor/github.com/sigstore/rekor/pkg/types/hashedrekord/v0.0.1/entry.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, ok-to-test
