Repository tektoncd/chains, pull requests merged in 2022-01, with the labels that each got.

#315 Allow IMAGES result to be separated by newlines
  docs/config.md
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
Labels: size/M, lgtm, approved

#318 Rely on cosign providers library for fulcio auth
  docs/config.md
  go.mod
  pkg/chains/signing/x509/x509.go
  pkg/config/config.go
  pkg/config/store_test.go
  test/e2e_test.go
  test/test_utils.go
  vendor/github.com/sigstore/cosign/pkg/providers/doc.go
  vendor/github.com/sigstore/cosign/pkg/providers/google/doc.go
  vendor/github.com/sigstore/cosign/pkg/providers/google/google.go
  vendor/github.com/sigstore/cosign/pkg/providers/interface.go
  vendor/google.golang.org/api/impersonate/doc.go
  vendor/google.golang.org/api/impersonate/idtoken.go
  vendor/google.golang.org/api/impersonate/impersonate.go
  vendor/google.golang.org/api/impersonate/user.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#327 Use cosign flags with 2 hyphens
  docs/tutorials/signed-provenance-tutorial.md
  test/kaniko.go
Labels: size/XS, lgtm, approved

#331 Make builder id for SLSA provenance valid URI
  pkg/chains/formats/provenance/provenance_test.go
  pkg/config/config.go
  pkg/config/store_test.go
  test/testdata/intoto/task-output-image.json
Labels: size/M, lgtm, approved, ok-to-test

#333 Move the underscore import to `package main`.
  cmd/controller/main.go
  pkg/chains/signing/x509/x509.go
Labels: size/XS, lgtm, approved

#337 Fix in-toto chains docs typos
  docs/intoto.md
Labels: size/XS, lgtm, approved, ok-to-test

#330 Update tutorial
  docs/tutorials/getting-started-tutorial.md
Labels: size/M, lgtm, approved, ok-to-test

#334 Remove un-used options from `artifacts.oci.format` and `artifacts.oci.storage`
  docs/config.md
  pkg/config/config.go
  test/e2e_test.go
Labels: size/XS, lgtm, approved, ok-to-test

#338 Add `chains-info` ConfigMap with version info
  config/100-rolebinding.yaml
  config/config-info.yaml
Labels: size/M, lgtm, approved

#342 Update go-containerregistry for permissions fix
  go.mod
  go.sum
  vendor/github.com/google/go-containerregistry/internal/gzip/zip.go
  vendor/github.com/google/go-containerregistry/internal/verify/verify.go
  vendor/github.com/google/go-containerregistry/pkg/authn/README.md
  vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go
  vendor/github.com/google/go-containerregistry/pkg/name/check.go
  vendor/github.com/google/go-containerregistry/pkg/v1/layout/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/mutate/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/compressed.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/error.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/ping.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/transport.go
  vendor/github.com/google/go-containerregistry/pkg/v1/stream/layer.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/exec_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/modules.txt
Labels: lgtm, size/S, approved

#346 Add securityContext to controller pod
  config/100-deployment.yaml
Labels: size/XS, lgtm, approved

#357 Fix namespace typo
  DEVELOPMENT.md
Labels: size/XS, lgtm, approved
