Repository tektoncd/chains, pull requests merged in 2022-06, with the labels that each got.

#461 Add ppc64le arch support to chains
  release/release-pipeline.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#464 Fix error msg in case no image produced
  pkg/chains/storage/oci/oci.go
  pkg/chains/storage/oci/oci_test.go
Labels: size/M, lgtm, approved, ok-to-test

#466 Add wlynch to OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#475 Update release doc
  release/README.md
Labels: lgtm, size/S, approved

#474 Update Readme
  README.md
Labels: size/XS, lgtm, approved, ok-to-test
