Repository tektoncd/chains, pull requests merged in 2022-08, with the labels that each got.

#505 Fix typo in v0.3.0-build-chains-taskrun.yaml.
  examples/releases/v0.3.0-build-chains-taskrun.yaml
Labels: size/XS, lgtm, approved

#506 Add more supported GCP KMS key ref formats in config doc
  docs/config.md
Labels: size/XS, lgtm, approved

#512 Pinning sigstore/scaffolding/actions/setup version
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#513 Pin to scaffolding v0.4.2, test with k8s 1.22, 1.23, and 1.24.
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#509 Use industry standard names for payloadType field
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
Labels: size/XS, lgtm, approved

#511 Add pull_request_template.md.
  .github/pull_request_template.md
Labels: lgtm, size/S, kind/documentation, approved

#519 Fix for issue #515, This PR ensures only those signers which are specified as signers for any artifact are initialized.
  pkg/chains/signing.go
  pkg/chains/signing_test.go
Labels: size/M, lgtm, approved

#518 Bump to use scaffolding v0.4.3.
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#503 Update config doc on the grafeas note part.
  docs/config.md
Labels: lgtm, size/S, approved

#529 bump to newer / more stable version of scaffolding. 0.25.0 of cli.
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#531 Grafeas storage for non-image artifacts
  pkg/artifacts/signable.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
Labels: kind/feature, size/M, lgtm, approved

#495 Make grafeas notehint configurable and change the BuildType field
  docs/config.md
  pkg/chains/formats/intotoite6/intotoite6.go
  pkg/chains/formats/intotoite6/intotoite6_test.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/config/config.go
  pkg/config/store_test.go
  test/testdata/intoto/task-output-image.json
Labels: size/L, lgtm, approved

#527 Fix param value ordering in materials
  pkg/chains/formats/intotoite6/intotoite6.go
  pkg/chains/formats/intotoite6/intotoite6_test.go
  pkg/chains/formats/intotoite6/testdata/taskrun1.json
  pkg/chains/formats/intotoite6/testdata/taskrun2.json
Labels: size/M, lgtm, approved

#537 Fix version tag environment variable.
  release/README.md
Labels: lgtm, size/S, approved

#532 Fix linting issues
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/chains/storage/oci/oci_test.go
Labels: lgtm, size/S, approved
