Repository tektoncd/chains, pull requests merged in 2022-12, with the labels that each got.

#644 Added GHA to run go vet and go fmt checks.
  .github/workflows/goclean.yml
Labels: size/M, lgtm, approved

#648 test/test_utils: Use kind instead of full GVK for tkn commands.
  test/test_utils.go
Labels: size/XS, lgtm, approved

#603 Generalize format loading.
  pkg/artifacts/signable.go
  pkg/chains/formats/all/all.go
  pkg/chains/formats/format.go
  pkg/chains/formats/intotoite6/intotoite6.go
  pkg/chains/formats/intotoite6/intotoite6_test.go
  pkg/chains/formats/simple/simple.go
  pkg/chains/formats/simple/simple_test.go
  pkg/chains/formats/tekton/tekton.go
  pkg/chains/formats/tekton/tekton_test.go
  pkg/chains/signing.go
  pkg/chains/signing_test.go
  pkg/config/options.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/taskrun/controller.go
Labels: size/L, lgtm, approved

#652 Promote Sigstore features out of experimental.
  docs/experimental.md
  docs/sigstore.md
Labels: size/L, lgtm, approved

#653 Update releases for v0.14.0
  README.md
  releases.md
Labels: size/M, lgtm, approved

#654 Move cloud vendor specific docs into their own folder.
  README.md
  docs/vendor/openshift.md
Labels: size/L, lgtm, approved

#660 Cleanup: replaced deprecated `ioutil` package use.
  pkg/chains/signing/wrap.go
  pkg/chains/signing/x509/x509.go
  pkg/chains/signing/x509/x509_test.go
  pkg/chains/storage/gcs/gcs.go
Labels: lgtm, size/S, approved, kind/cleanup
