Repository tektoncd/chains, pull requests merged in 2022-09, with the labels that each got.

#538 Remove use of pipeline/v1alpha1
  pkg/chains/formats/intotoite6/intotoite6.go
  test/e2e_test.go
Labels: lgtm, size/S, approved

#541 Add reviewers section to OWNERS file.
  OWNERS
Labels: size/XS, lgtm, approved

#539 Bump e2e workflow to Go 1.18.
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved, kind/misc

#436 TEP-84: PipelineRun Attestations
  cmd/controller/main.go
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
  pkg/chains/annotations.go
  pkg/chains/annotations_test.go
  pkg/chains/formats/intotoite6/attest/attest.go
  pkg/chains/formats/intotoite6/extract/extract.go
  pkg/chains/formats/intotoite6/intotoite6.go
  pkg/chains/formats/intotoite6/intotoite6_test.go
  pkg/chains/formats/intotoite6/pipelinerun/pipelinerun.go
  pkg/chains/formats/intotoite6/pipelinerun/provenance_test.go
  pkg/chains/formats/intotoite6/taskrun/buildconfig.go
  pkg/chains/formats/intotoite6/taskrun/buildconfig_test.go
  pkg/chains/formats/intotoite6/taskrun/provenance_test.go
  pkg/chains/formats/intotoite6/taskrun/taskrun.go
  pkg/chains/formats/intotoite6/testdata/pipelinerun-childrefs.json
  pkg/chains/formats/intotoite6/testdata/pipelinerun1.json
  pkg/chains/formats/intotoite6/testdata/taskrun1.json
  pkg/chains/formats/intotoite6/testdata/taskrun2.json
  pkg/chains/formats/tekton/tekton.go
  pkg/chains/formats/tekton/tekton_test.go
  pkg/chains/objects/objects.go
  pkg/chains/rekor.go
  pkg/chains/rekor_test.go
  pkg/chains/signing.go
  pkg/chains/signing_test.go
  pkg/chains/storage/docdb/docdb.go
  pkg/chains/storage/docdb/docdb_test.go
  pkg/chains/storage/gcs/gcs.go
  pkg/chains/storage/gcs/gcs_test.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/chains/storage/oci/oci.go
  pkg/chains/storage/oci/oci_test.go
  pkg/chains/storage/pubsub/pubsub.go
  pkg/chains/storage/pubsub/pubsub_test.go
  pkg/chains/storage/storage.go
  pkg/chains/storage/tekton/tekton.go
  pkg/chains/storage/tekton/tekton_test.go
  pkg/chains/verifier.go
  pkg/config/config.go
  pkg/config/store_test.go
  pkg/internal/mocksigner/mocksigner.go
  pkg/internal/objectloader/objectloader.go
  pkg/internal/tekton/tekton.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
  test/test_utils.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun/controller.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun/reconciler.go
  vendor/github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun/state.go
  vendor/github.com/tektoncd/pipeline/pkg/status/status.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved, ok-to-test

#570 test with scaffolding 0.4.8
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#568 Update PipelineRun attestation buildType
  pkg/chains/formats/intotoite6/intotoite6_test.go
  pkg/chains/formats/intotoite6/pipelinerun/pipelinerun.go
  pkg/chains/formats/intotoite6/taskrun/taskrun.go
Labels: lgtm, size/S, approved
