Repository tektoncd/chains, pull requests merged in 2023-06, with the labels that each got.

#800 Slsa1.0 params, builderID, buildType, subjects, metadata, byProducts
  pkg/chains/formats/all/all.go
  pkg/chains/formats/format.go
  pkg/chains/formats/slsa/testdata/v2alpha2/pipelinerun1.json
  pkg/chains/formats/slsa/testdata/v2alpha2/pipelinerun_structured_results.json
  pkg/chains/formats/slsa/testdata/v2alpha2/taskrun-multiple-subjects.json
  pkg/chains/formats/slsa/testdata/v2alpha2/taskrun1.json
  pkg/chains/formats/slsa/testdata/v2alpha2/taskrun2.json
  pkg/chains/formats/slsa/v2alpha2/internal/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v2alpha2/internal/pipelinerun/pipelinerun_test.go
  pkg/chains/formats/slsa/v2alpha2/internal/resolved_dependencies/resolved_dependencies_test.go
  pkg/chains/formats/slsa/v2alpha2/internal/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha2/internal/taskrun/taskrun_test.go
  pkg/chains/formats/slsa/v2alpha2/slsav2.go
  pkg/chains/formats/slsa/v2alpha2/slsav2_test.go
Labels: kind/feature, lgtm, size/XXL, approved

#823 SLSAv1.0 predicate format wire-up
  pkg/chains/formats/slsa/README.md
  pkg/config/config.go
  test/examples_test.go
  test/testdata/slsa/v2alpha2/pipeline-output-image.json
  test/testdata/slsa/v2alpha2/task-output-image.json
Labels: kind/feature, size/L, lgtm, approved

#826 List the slsa/v2* formats in the in-toto set
  pkg/chains/formats/all/all.go
  pkg/chains/formats/format.go
  pkg/chains/formats/slsa/v2alpha1/README.md
  pkg/chains/formats/slsa/v2alpha1/slsav2.go
  pkg/chains/formats/slsa/v2alpha1/slsav2_test.go
  pkg/chains/formats/slsa/v2alpha1/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha1/taskrun/taskrun_test.go
Labels: lgtm, size/S, approved

#831 Add metrics docs.
  docs/metrics.md
Labels: lgtm, size/S, approved

#836 add ConfigMap and Service for observability
  config/100-deployment.yaml
  config/config-observability.yaml
  config/observability-service.yaml
Labels: size/L, lgtm, approved, ok-to-test
