Repository tektoncd/chains, pull requests merged in 2023-01, with the labels that each got.

#662 Cleanup: use idiomatic Go.
  pkg/chains/storage/oci/oci.go
  pkg/chains/storage/oci/oci_test.go
  test/clients.go
  test/e2e_test.go
  test/examples_test.go
  test/kaniko.go
  test/test_utils.go
Labels: size/XL, lgtm, approved, kind/cleanup

#661 Cleaned up `golangci-lint` and added additional linters.
  .golang-ci.yaml
Labels: size/M, lgtm, approved, kind/cleanup

#649 Issue 642: predicate.materials needs to record more information in TaskRun
  pkg/chains/formats/intotoite6/internal/material/material.go
  pkg/chains/formats/intotoite6/internal/material/material_test.go
  pkg/chains/formats/intotoite6/intotoite6_test.go
  pkg/chains/formats/intotoite6/taskrun/material.go
  pkg/chains/formats/intotoite6/taskrun/material_test.go
  pkg/chains/formats/intotoite6/taskrun/provenance_test.go
  pkg/chains/formats/intotoite6/taskrun/taskrun.go
  test/examples_test.go
  test/sortoptions.go
  test/testdata/intoto/task-output-image.json
Labels: kind/bug, lgtm, size/XXL, approved

#668 Unexport intoto/taskrun funcs
  pkg/chains/formats/intotoite6/taskrun/material.go
  pkg/chains/formats/intotoite6/taskrun/material_test.go
Labels: lgtm, size/S, approved

#678 Fix to prevent adding empty structs into materials.
  pkg/chains/formats/intotoite6/pipelinerun/pipelinerun.go
  pkg/chains/formats/intotoite6/pipelinerun/provenance_test.go
  pkg/chains/formats/intotoite6/testdata/pipelinerun_structured_results.json
Labels: size/L, lgtm, approved

#658 Issue 642: Add sidecar, step and remote tasks to pipelinerun materials
  pkg/chains/formats/intotoite6/intotoite6_test.go
  pkg/chains/formats/intotoite6/pipelinerun/pipelinerun.go
  pkg/chains/formats/intotoite6/pipelinerun/provenance_test.go
  pkg/chains/formats/intotoite6/taskrun/material.go
  pkg/chains/formats/intotoite6/taskrun/material_test.go
  test/e2e_test.go
  test/examples_test.go
  test/sortoptions.go
  test/testdata/intoto/pipeline-output-image.json
Labels: kind/bug, size/L, lgtm, approved

#651 Run GHA workflows on release branches.
  .github/workflows/goclean.yml
  .github/workflows/kind-e2e.yaml
  .github/workflows/lint.yaml
Labels: lgtm, size/S, approved

#676 Fix checks to allow passing in of sha1 digests through StructuredResults.
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
Labels: kind/bug, size/M, lgtm, approved

#684 Updating provenance format branding from `intotoite` to `slsa` internally
  pkg/chains/formats/all/all.go
  pkg/chains/formats/slsa/attest/attest.go
  pkg/chains/formats/slsa/extract/extract.go
  pkg/chains/formats/slsa/extract/extract_test.go
  pkg/chains/formats/slsa/testdata/pipelinerun-childrefs.json
  pkg/chains/formats/slsa/testdata/pipelinerun1.json
  pkg/chains/formats/slsa/testdata/pipelinerun_structured_results.json
  pkg/chains/formats/slsa/testdata/taskrun-multiple-subjects.json
  pkg/chains/formats/slsa/testdata/taskrun1.json
  pkg/chains/formats/slsa/testdata/taskrun2.json
  pkg/chains/formats/slsa/v1/internal/material/material.go
  pkg/chains/formats/slsa/v1/internal/material/material_test.go
  pkg/chains/formats/slsa/v1/intotoite6.go
  pkg/chains/formats/slsa/v1/intotoite6_test.go
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/buildconfig.go
  pkg/chains/formats/slsa/v1/taskrun/buildconfig_test.go
  pkg/chains/formats/slsa/v1/taskrun/material.go
  pkg/chains/formats/slsa/v1/taskrun/material_test.go
  pkg/chains/formats/slsa/v1/taskrun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/taskrun.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
Labels: kind/feature, size/M, lgtm, approved

#632 add transparency log search ui provided by chainguard team
  docs/sigstore.md
Labels: lgtm, size/S, approved, ok-to-test

#685 Remove tekton as a provenance format
  docs/config.md
  docs/tutorials/getting-started-tutorial.md
  pkg/chains/formats/all/all.go
  pkg/chains/formats/tekton/tekton.go
  pkg/chains/formats/tekton/tekton_test.go
  pkg/chains/signing_test.go
  pkg/config/config.go
  pkg/config/store_test.go
  test/e2e_test.go
Labels: kind/feature, size/L, lgtm, approved

#687 Slsa Branding of Chains Provenance Format
  docs/config.md
  docs/intoto.md
  docs/tutorials/signed-provenance-tutorial.md
  pkg/chains/formats/format.go
  pkg/chains/formats/slsa/README.md
  pkg/chains/formats/slsa/v1/intotoite6.go
  pkg/chains/formats/slsa/v1/intotoite6_test.go
  pkg/chains/rekor.go
  pkg/chains/signing_test.go
  pkg/chains/storage/gcs/gcs_test.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/chains/storage/oci/oci.go
  pkg/chains/storage/oci/oci_test.go
  pkg/chains/storage/pubsub/pubsub_test.go
  pkg/config/config.go
  test/e2e_test.go
  test/examples_test.go
Labels: kind/feature, size/L, lgtm, approved

#693 Do not initialize Rekor client if transparency is not enabled. Issue #520
  README.md
  config/100-deployment.yaml
  pkg/chains/rekor.go
  pkg/chains/signing.go
  pkg/chains/signing_test.go
Labels: lgtm, size/S, approved
