Repository tektoncd/chains, pull requests merged in 2023-05, with the labels that each got.

#790 Re-add support for full task status for backward compatibility
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: kind/feature, size/L, lgtm, approved

#799 Migrate from Provenance.ConfigSource to Provenance.RefSource
  pkg/chains/formats/slsa/attest/attest.go
  pkg/chains/formats/slsa/testdata/pipelinerun1.json
  pkg/chains/formats/slsa/testdata/pipelinerun_structured_results.json
  pkg/chains/formats/slsa/testdata/taskrun-multiple-subjects.json
  pkg/chains/formats/slsa/testdata/taskrun1.json
  pkg/chains/formats/slsa/testdata/taskrun2.json
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2/taskrun/taskrun.go
Labels: size/M, lgtm, approved

#795 Manually bump in-toto-golang to v0.8.0
  go.mod
  go.sum
  vendor/github.com/in-toto/in-toto-golang/in_toto/keylib.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/model.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/slsa_provenance/v1/provenance.go
  vendor/github.com/in-toto/in-toto-golang/in_toto/verifylib.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/exec_windows.go
  vendor/golang.org/x/sys/windows/service.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: lgtm, size/S, approved

#792 Conform provenance.materials.uri to URI syntax
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
  pkg/chains/formats/slsa/attest/attest.go
  pkg/chains/formats/slsa/internal/material/material.go
  pkg/chains/formats/slsa/internal/material/material_test.go
  pkg/chains/formats/slsa/v1/intotoite6_test.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/buildconfig_test.go
  pkg/chains/formats/slsa/v2/README.md
  pkg/chains/formats/slsa/v2/slsav2_test.go
  test/e2e_test.go
  test/examples_test.go
  test/testdata/slsa/v1/pipeline-output-image.json
  test/testdata/slsa/v1/task-output-image.json
Labels: size/L, lgtm, approved, ok-to-test

#804 Bump knative.dev/pkg
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/limitrange/limitrange.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/filtered/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/serviceaccount/serviceaccount.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/ptr/doc.go
  vendor/knative.dev/pkg/ptr/ptr.go
  vendor/knative.dev/pkg/ptr/value.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#798 Introduce Resolved dependencies for SLSA v1.0 predicate
  pkg/artifacts/signable.go
  pkg/chains/formats/slsa/internal/material/material.go
  pkg/chains/formats/slsa/internal/material/material_test.go
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v2alpha2/internal/resolved_dependencies/resolved_dependencies.go
  pkg/chains/formats/slsa/v2alpha2/internal/resolved_dependencies/resolved_dependencies_test.go
Labels: kind/feature, lgtm, size/XXL, approved

#796 Remove update_licenses call.
  hack/update-deps.sh
Labels: size/XS, lgtm, approved

#814 Use mount secrets in OCI backend
  docs/authentication.md
  go.mod
  go.sum
  pkg/chains/storage/oci/oci.go
  vendor/github.com/google/go-containerregistry/pkg/authn/kubernetes/keychain.go
  vendor/modules.txt
Labels: lgtm, size/S, approved
