Repository tektoncd/chains, pull requests merged in 2023-04, with the labels that each got.

#754 Update lint workflow
  .github/workflows/lint.yaml
Labels: size/XS, lgtm, approved

#758 Cleanup duplicate imports
  pkg/chains/objects/objects.go
Labels: size/XS, lgtm, approved

#765 Use `common` package from intoto-golang.
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
  pkg/chains/formats/slsa/extract/extract.go
  pkg/chains/formats/slsa/internal/material/material.go
  pkg/chains/formats/slsa/internal/material/material_test.go
  pkg/chains/formats/slsa/v1/intotoite6_test.go
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2/slsav2_test.go
  pkg/chains/formats/slsa/v2/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2/taskrun/taskrun_test.go
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/chains/storage/oci/oci_test.go
Labels: size/L, lgtm, approved

#769 e2e: Adds basic e2e test for Pipelines LTS versions.
  .github/workflows/kind-e2e.yaml
  .github/workflows/reusable-e2e.yaml
Labels: size/L, lgtm, approved

#771 Bump knative.dev/pkg
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/OWNERS
  vendor/knative.dev/pkg/apis/duck/OWNERS
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/configmap/OWNERS
  vendor/knative.dev/pkg/controller/OWNERS
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/hash/OWNERS
  vendor/knative.dev/pkg/injection/OWNERS
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/OWNERS
  vendor/knative.dev/pkg/logging/OWNERS
  vendor/knative.dev/pkg/metrics/OWNERS
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/OWNERS
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/OWNERS
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/config/OWNERS
  vendor/knative.dev/pkg/webhook/OWNERS
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#763 Set metadata completeness for parameters as true for slsav2/alpha1
  pkg/chains/formats/slsa/v2/slsav2_test.go
  pkg/chains/formats/slsa/v2/taskrun/taskrun.go
  test/testdata/slsa/v2/task-output-image.json
Labels: kind/feature, lgtm, size/S, approved

#773 Prune OWNERS file.
  OWNERS
Labels: lgtm, size/S, approved

#776 Cleanup: generics replace deprecated sets.String.
  pkg/artifacts/signable.go
  pkg/chains/signing.go
  pkg/chains/signing_test.go
  pkg/chains/storage/storage.go
  pkg/chains/storage/storage_test.go
  pkg/chains/verifier.go
  pkg/config/config.go
  pkg/config/store_test.go
  pkg/config/zz_generated.deepcopy.go
  test/test_utils.go
Labels: size/L, lgtm, approved, kind/cleanup

#777 Hygiene: enabled presets properly.
  .golang-ci.yaml
Labels: lgtm, size/S, approved

#778 Remove log parameters in favor of context based logging.
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
  pkg/chains/formats/slsa/extract/extract.go
  pkg/chains/formats/slsa/extract/extract_test.go
  pkg/chains/formats/slsa/internal/material/material.go
  pkg/chains/formats/slsa/internal/material/material_test.go
  pkg/chains/formats/slsa/v1/intotoite6.go
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2/slsav2.go
  pkg/chains/formats/slsa/v2/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2/taskrun/taskrun_test.go
  pkg/chains/rekor.go
  pkg/chains/signing.go
  pkg/chains/signing/kms/kms.go
  pkg/chains/signing/x509/x509.go
  pkg/chains/signing/x509/x509_test.go
  pkg/chains/signing_test.go
  pkg/chains/storage/docdb/docdb.go
  pkg/chains/storage/docdb/docdb_test.go
  pkg/chains/storage/gcs/gcs.go
  pkg/chains/storage/gcs/gcs_test.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/chains/storage/oci/oci.go
  pkg/chains/storage/oci/oci_test.go
  pkg/chains/storage/pubsub/pubsub.go
  pkg/chains/storage/pubsub/pubsub_test.go
  pkg/chains/storage/storage.go
  pkg/chains/storage/storage_test.go
  pkg/chains/storage/tekton/tekton.go
  pkg/chains/storage/tekton/tekton_test.go
  pkg/chains/verifier.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/taskrun/controller.go
  test/test_utils.go
Labels: size/L, lgtm, approved

#779 Replace deprecated type/function
  pkg/artifacts/signable_test.go
  pkg/chains/formats/slsa/attest/attest.go
  pkg/chains/formats/slsa/v1/intotoite6_test.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/provenance_test.go
  pkg/chains/formats/slsa/v2/taskrun/taskrun_test.go
  pkg/chains/objects/objects.go
  pkg/chains/objects/objects_test.go
  pkg/chains/storage/tekton/tekton_test.go
  test/e2e_test.go
  test/kaniko.go
Labels: size/L, lgtm, approved, kind/cleanup

#781 Hygiene: Enabled new linters and increased timeout.
  .golang-ci.yaml
Labels: lgtm, size/S, approved

#783 Use resource package for resource variable
  pkg/artifacts/signable.go
Labels: size/XS, lgtm, approved
