Repository tektoncd/chains, pull requests merged in 2023-09, with the labels that each got.

#907 docs: Ensure the storage backend to store OCI signatures is set to oci
  docs/tutorials/signed-provenance-tutorial.md
Labels: size/XS, lgtm, approved, ok-to-test

#896 Increase direct usage of Tekton Object Interface
  pkg/chains/formats/slsa/attest/attest.go
  pkg/chains/formats/slsa/extract/extract.go
  pkg/chains/formats/slsa/internal/material/material.go
  pkg/chains/formats/slsa/internal/material/material_test.go
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha2/internal/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v2alpha2/internal/resolved_dependencies/resolved_dependencies.go
  pkg/chains/formats/slsa/v2alpha2/internal/taskrun/taskrun.go
  pkg/chains/objects/objects.go
  pkg/chains/objects/objects_test.go
Labels: size/L, lgtm, approved, kind/cleanup

#924 Refactor StructuredSignable extraction
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
  pkg/artifacts/structured.go
Labels: size/L, lgtm, approved

#927 document buildType config
  docs/config.md
Labels: lgtm, size/S, approved, ok-to-test

#933 Fixes Hashivault configuration with Chains
  pkg/chains/signing/kms/kms.go
  pkg/chains/signing/kms/kms_test.go
Labels: size/M, lgtm, approved

#928 Make buildConfigSource test support non-deterministic ref
  pkg/chains/formats/slsa/v2alpha2/internal/external_parameters/external_parameters_test.go
Labels: lgtm, size/S, approved, ok-to-test
