Repository tektoncd/chains, pull requests merged in 2023-07, with the labels that each got.

#842 v1: Rewrite OCI storage to use new interface
  docs/v1-proposal.md
  pkg/chains/signing/iface.go
  pkg/chains/storage/api/api.go
  pkg/chains/storage/oci/attestation.go
  pkg/chains/storage/oci/legacy.go
  pkg/chains/storage/oci/options.go
  pkg/chains/storage/oci/simple.go
Labels: size/XL, lgtm, approved

#857 Cleanup Materials usage
  pkg/chains/formats/slsa/internal/material/material.go
  pkg/chains/formats/slsa/internal/material/material_test.go
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha1/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha2/internal/resolved_dependencies/resolved_dependencies.go
Labels: size/L, lgtm, approved, kind/cleanup

#863 Add top-level build config to External Parameters
  pkg/chains/formats/slsa/v2alpha2/internal/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v2alpha2/internal/pipelinerun/pipelinerun_test.go
  pkg/chains/formats/slsa/v2alpha2/internal/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha2/internal/taskrun/taskrun_test.go
Labels: kind/feature, size/M, lgtm, approved

#867 [v1] Update tekton storage backend to use Storer interface.
  pkg/chains/storage/tekton/tekton.go
Labels: size/M, lgtm, approved

#872 Update releases.md
  release/README.md
  releases.md
Labels: size/L, lgtm, approved

#851 [v1] storage/gcs: Adapt Backend to new Storer interface.
  pkg/chains/storage/gcs/gcs.go
Labels: size/L, lgtm, approved

#876 Enable `docdb` for `artifacts.pipelinerun.storage`
  pkg/chains/storage/docdb/docdb_test.go
  pkg/config/config.go
  pkg/config/store_test.go
Labels: size/M, lgtm, approved, ok-to-test

#877 Make chitrangpatel a maintainer
  OWNERS
Labels: size/XS, lgtm, approved

#859 Enable grouped dependabot updates.
  .github/dependabot.yml
Labels: size/XS, lgtm, approved

#878 Fix test data json
  pkg/chains/formats/slsa/testdata/v2alpha2/taskrun1.json
Labels: lgtm, size/S, approved

#886 Update releases with v0.17.0
  releases.md
Labels: lgtm, size/S, approved

#885 Pass slsa-related config via explicit struct instead of separate args
  pkg/chains/formats/slsa/internal/slsaconfig/slsaconfig.go
  pkg/chains/formats/slsa/v1/intotoite6.go
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha2/internal/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v2alpha2/internal/pipelinerun/pipelinerun_test.go
  pkg/chains/formats/slsa/v2alpha2/internal/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha2/internal/taskrun/taskrun_test.go
  pkg/chains/formats/slsa/v2alpha2/slsav2.go
Labels: size/M, lgtm, approved
