Repository tektoncd/chains, pull requests merged in 2023-08, with the labels that each got.

#866 Smarter Chains: check taskrun level results for Subjects
  docs/config.md
  pkg/chains/formats/slsa/extract/extract.go
  pkg/chains/formats/slsa/extract/extract_test.go
  pkg/chains/formats/slsa/internal/slsaconfig/slsaconfig.go
  pkg/chains/formats/slsa/testdata/taskrun-multiple-subjects.json
  pkg/chains/formats/slsa/testdata/v2alpha2/taskrun-multiple-subjects.json
  pkg/chains/formats/slsa/v1/intotoite6.go
  pkg/chains/formats/slsa/v1/intotoite6_test.go
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha1/slsav2_test.go
  pkg/chains/formats/slsa/v2alpha1/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha1/taskrun/taskrun_test.go
  pkg/chains/formats/slsa/v2alpha2/internal/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v2alpha2/internal/pipelinerun/pipelinerun_test.go
  pkg/chains/formats/slsa/v2alpha2/internal/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha2/slsav2.go
  pkg/chains/formats/slsa/v2alpha2/slsav2_test.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/config/config.go
  pkg/config/store_test.go
Labels: size/L, lgtm, approved

#898 Fix typo in dependabot.yml
  .github/dependabot.yml
Labels: size/XS, lgtm, approved

#901 Adds a tutorial example for Hashicorp Integration with Tekton Chains using KMS solution
  docs/tutorials/hashicorp-integration-tutorial.md
Labels: size/L, lgtm, approved

#904 Fix SPDX format function
  pkg/chains/formats/slsa/attest/attest.go
  pkg/chains/formats/slsa/internal/material/material_test.go
Labels: kind/bug, lgtm, size/S, approved

#910 Bump e2e tests for Pipeline v0.50, v0.51
  .github/workflows/kind-e2e.yaml
Labels: lgtm, size/S, approved

#911 Make e2e tests faster
  test/clients.go
  test/examples_test.go
  test/test_utils.go
Labels: size/M, lgtm, approved, kind/cleanup
