Repository tektoncd/chains, pull requests merged in 2023-11, with the labels that each got.

#970 Remove PipelineResource section from release notes.
  release/README.md
Labels: lgtm, size/S, approved

#978 docs: Show configuration section in main documentation
  docs/config.md
  docs/slsa-provenance.md
Labels: size/XS, lgtm, approved, ok-to-test

#974 Fixes value for storage.oci.repository
  pkg/chains/storage/oci/legacy.go
  pkg/chains/storage/oci/legacy_test.go
Labels: size/M, lgtm, approved
