Repository tektoncd/chains, pull requests merged in 2023-10, with the labels that each got.

#930 Update releases with v0.18.0
  releases.md
Labels: size/XS, lgtm, approved

#926 Handle duplicates in subjects and materials consistently
  pkg/chains/formats/slsa/extract/extract.go
  pkg/chains/formats/slsa/internal/artifact/append.go
  pkg/chains/formats/slsa/internal/artifact/append_test.go
  pkg/chains/formats/slsa/internal/material/material.go
  pkg/chains/formats/slsa/internal/material/material_test.go
Labels: kind/bug, size/XL, lgtm, approved

#944 Remove priyawadhwa from active reviewers
  OWNERS
Labels: size/XS, lgtm, approved

#913 Add user-facing doc "SLSA Provenance"
  docs/config.md
  docs/intoto.md
  docs/slsa-provenance.md
  images/how-chains-works.png
Labels: size/XL, lgtm, approved

#946 Remove chuangw6 from active reviewers
  OWNERS
Labels: size/XS, lgtm, approved

#936 Fixes hashivault connection check
  pkg/chains/signing/kms/kms.go
  pkg/chains/signing/kms/kms_test.go
Labels: size/L, lgtm, approved

#960 Removes unused context from the wrap function
  pkg/chains/signing.go
  pkg/chains/signing/wrap.go
Labels: size/XS, lgtm, approved

#973 Update releases.md for v0.19.0
  releases.md
Labels: lgtm, size/S, approved

#971 feat: add PipelineRun support to storage/gcs
  pkg/chains/storage/gcs/gcs.go
  pkg/chains/storage/gcs/gcs_test.go
Labels: size/L, lgtm, approved
