Repository tektoncd/chains, pull requests merged in 2023-02, with the labels that each got.

#692 Add labels and annotations to attestation
  docs/intoto.md
  pkg/chains/formats/slsa/attest/attest.go
  pkg/chains/formats/slsa/v1/intotoite6_test.go
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/taskrun.go
  test/examples_test.go
Labels: size/L, lgtm, approved

#706 Retain material ordering when pruning duplicates.
  pkg/chains/formats/slsa/v1/internal/material/material.go
  pkg/chains/formats/slsa/v1/internal/material/material_test.go
  pkg/chains/formats/slsa/v1/intotoite6_test.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/material.go
  pkg/chains/formats/slsa/v1/taskrun/material_test.go
  test/examples_test.go
  test/sortoptions.go
Labels: size/L, lgtm, approved

#708 Fix getting started docs for intoto verification.
  docs/tutorials/getting-started-tutorial.md
Labels: size/XS, lgtm, approved

#709 Remove references to slsa/v2alpha1 in top level docs.
  docs/config.md
Labels: size/XS, lgtm, approved

#704 Prevent duplicate attestations
  pkg/chains/annotations.go
  pkg/chains/annotations_test.go
  pkg/chains/signing_test.go
  pkg/reconciler/pipelinerun/pipelinerun.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: size/L, lgtm, approved

#719 Add additional documentation for other KMS key refs + link to Sigstore
  docs/config.md
Labels: size/XS, lgtm, approved

#718 Update config docs to remove experimental label from sigstore features.
  docs/config.md
Labels: lgtm, size/S, approved

#720 [TEP0122] Add feature flags field to Invocation.Environment
  pkg/chains/formats/slsa/v2/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2/taskrun/taskrun_test.go
Labels: kind/feature, size/M, lgtm, approved

#724 [TEP0122]: Add example showing provenance in README
  pkg/chains/formats/slsa/v2/README.md
Labels: size/L, lgtm, kind/documentation, approved

#725 Update docs for cosign v2
  docs/tutorials/getting-started-tutorial.md
Labels: size/XS, lgtm, kind/documentation, approved

#729 Fix docs/config.md typos
  docs/config.md
Labels: size/XS, lgtm, approved, ok-to-test
