Repository tektoncd/chains, pull requests merged in 2023-03, with the labels that each got.

#731 Hygiene: enable additional linters.
  .golang-ci.yaml
Labels: lgtm, size/S, approved, kind/cleanup

#733 .github/workflows: switch go to 1.19…
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#735 Hygiene: enable additional linters.
  .golang-ci.yaml
Labels: lgtm, size/S, approved, kind/cleanup

#737 Update project to go 1.19
  .github/workflows/goclean.yml
  go.mod
Labels: lgtm, size/S, approved

#749 Remove unwanted comments, bump e2e tests to v0.45.0
  .github/workflows/kind-e2e.yaml
  pkg/config/config.go
Labels: lgtm, size/S, approved
