Repository tektoncd/chains, pull requests merged in 2024-02, with the labels that each got.

#1043 Document the metrics provided by chains controller to fix #1041
  docs/metrics.md
Labels: lgtm, size/S, approved, ok-to-test

#1048 Adds custom namespace in e2e tests
  test/clients.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e_test.go
  test/test_utils.go
Labels: size/M, lgtm, approved

#1052 Corrected logic when token file provided
  pkg/chains/signing/x509/x509.go
  pkg/chains/signing/x509/x509_test.go
Labels: lgtm, size/S, approved, ok-to-test

#1063 chore: add aaron-prindle to OWNERS reviewers list
  OWNERS
Labels: size/XS, lgtm, approved
