Repository tektoncd/chains, pull requests merged in 2024-08, with the labels that each got.

#1171 Remove unnecessary fmt statement
  pkg/chains/formats/slsa/internal/resolved_dependencies/resolved_dependencies.go
Labels: size/XS, lgtm, approved

#1167 Make kms path generic to read from a file path instead of `KMS_AUTH_TOKEN`
  docs/config.md
  docs/signing.md
  pkg/chains/signing/kms/kms.go
  pkg/chains/signing/kms/kms_test.go
  pkg/config/config.go
Labels: size/M, lgtm, approved

#1179 Fix flaky watch backend test
  pkg/chains/storage/docdb/docdb_test.go
Labels: size/M, lgtm, approved

#1183 Includes visual guide representing chains config options
  docs/config.md
  images/signing-storage-config-diagram.drawio.svg
Labels: size/XL, lgtm, approved, ok-to-test
