Repository tektoncd/chains, pull requests merged in 2024-10, with the labels that each got.

#1220 Prepare release pipeline for ghcr.io
  release/publish.yaml
  release/release-pipeline.yaml
Labels: size/L, lgtm, approved

#1221 Fix indentation in release file
  release/release-pipeline.yaml
Labels: kind/bug, size/XS, lgtm, approved

#1222 Fix the path to the publish task
  release/release-pipeline.yaml
Labels: size/XS, lgtm, approved, kind/misc

#1207 Disable flaky TestWatchBackend test
  pkg/chains/storage/docdb/docdb_test.go
Labels: lgtm, size/S, approved

#1213 Support mongo server url path
  docs/config.md
  pkg/chains/storage/docdb/docdb.go
  pkg/config/config.go
Labels: size/L, lgtm, approved

#1228 Use ubuntu 22.04 temporarly to fix the E2E
  .github/workflows/reusable-e2e.yaml
Labels: size/XS, lgtm, approved, kind/misc

#1230 Bump sigsture scaffolding to v0.7.12
  .github/workflows/reusable-e2e.yaml
Labels: size/XS, lgtm, approved

#1237 fix nil pointer dereference when taksrun is canceled
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
Labels: size/XS, lgtm, approved
