Repository tektoncd/chains, pull requests merged in 2024-01, with the labels that each got.

#1025 Change Leader Election Config Map for Chains Controller
  config/100-deployment.yaml
  config/config-leader-election.yaml
Labels: kind/feature, size/M, lgtm, approved

#1034 Add metrics for count chains attestation for issue#1028
  pkg/chains/constants.go
  pkg/chains/signing.go
  pkg/pipelinerunmetrics/fake/fake.go
  pkg/pipelinerunmetrics/injection.go
  pkg/pipelinerunmetrics/metrics.go
  pkg/pipelinerunmetrics/metrics_test.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun_test.go
  pkg/taskrunmetrics/fake/fake.go
  pkg/taskrunmetrics/injection.go
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/metricstest/resource_metrics.go
  vendor/knative.dev/pkg/metrics/testing/config.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved, ok-to-test

#1040 Add v0.20 release
  releases.md
Labels: size/M, lgtm, approved
