Repository tektoncd/chains, pull requests merged in 2024-11, with the labels that each got.

#1202 Bootstrap crc in github action
  .github/workflows/test-on-crc.yaml
  test/crc_test.sh
  test/e2e_test.go
  test/kaniko.go
Labels: size/L, lgtm, approved

#1248 fix nil pointer
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
Labels: lgtm, size/S, approved

#1241 Fix release instructions
  release/README.md
  release/publish.yaml
  release/release-pipeline.yaml
  releases.md
Labels: size/M, lgtm
