Repository tektoncd/chains, pull requests merged in 2024-06, with the labels that each got.

#1129 Fix field names in generated json statement
  pkg/chains/signing.go
  pkg/chains/signing_test.go
  test/testdata/slsa/v1/pipeline-output-image.json
  test/testdata/slsa/v1/task-output-image.json
  test/testdata/slsa/v2/task-output-image.json
  test/testdata/slsa/v2alpha3/pipeline-output-image.json
  test/testdata/slsa/v2alpha3/task-output-image.json
  test/testdata/slsa/v2alpha4/pipeline-output-image.json
  test/testdata/slsa/v2alpha4/pipeline-with-object-type-hinting.json
  test/testdata/slsa/v2alpha4/task-output-image.json
  test/testdata/slsa/v2alpha4/task-with-object-type-hinting.json
Labels: size/L, lgtm, approved, ok-to-test

#1130 Fix no repeated subjects for v2alpha4 pipelineruns
  examples/v2alpha4/pipeline-with-repeated-results.yaml
  pkg/chains/formats/slsa/testdata/slsa-v2alpha4/pipelinerun2.json
  pkg/chains/formats/slsa/testdata/slsa-v2alpha4/taskrun3.json
  pkg/chains/formats/slsa/testdata/slsa-v2alpha4/taskrun4.json
  pkg/chains/formats/slsa/v2alpha4/internal/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v2alpha4/internal/pipelinerun/pipelinerun_test.go
  test/examples_test.go
  test/testdata/slsa/v2alpha4/pipeline-with-repeated-results.json
Labels: lgtm, size/XXL, approved, ok-to-test

#1132 Calculate subjects per formatter
  pkg/chains/formats/format.go
  pkg/chains/formats/simple/simple.go
  pkg/chains/formats/slsa/v1/intotoite6.go
  pkg/chains/formats/slsa/v2alpha3/slsav2.go
  pkg/chains/formats/slsa/v2alpha4/internal/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v2alpha4/slsav2.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
Labels: size/L, lgtm, approved

#1134 Fixes for v0.21.1
  examples/v2alpha4/pipeline-with-repeated-results.yaml
  pkg/chains/formats/format.go
  pkg/chains/formats/simple/simple.go
  pkg/chains/formats/slsa/testdata/slsa-v2alpha4/pipelinerun2.json
  pkg/chains/formats/slsa/testdata/slsa-v2alpha4/taskrun3.json
  pkg/chains/formats/slsa/testdata/slsa-v2alpha4/taskrun4.json
  pkg/chains/formats/slsa/v1/intotoite6.go
  pkg/chains/formats/slsa/v2alpha3/slsav2.go
  pkg/chains/formats/slsa/v2alpha4/internal/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v2alpha4/internal/pipelinerun/pipelinerun_test.go
  pkg/chains/formats/slsa/v2alpha4/slsav2.go
  pkg/chains/signing.go
  pkg/chains/signing_test.go
  pkg/chains/storage/grafeas/grafeas.go
  pkg/chains/storage/grafeas/grafeas_test.go
  test/examples_test.go
  test/testdata/slsa/v1/pipeline-output-image.json
  test/testdata/slsa/v1/task-output-image.json
  test/testdata/slsa/v2/task-output-image.json
  test/testdata/slsa/v2alpha3/pipeline-output-image.json
  test/testdata/slsa/v2alpha3/task-output-image.json
  test/testdata/slsa/v2alpha4/pipeline-output-image.json
  test/testdata/slsa/v2alpha4/pipeline-with-object-type-hinting.json
  test/testdata/slsa/v2alpha4/pipeline-with-repeated-results.json
  test/testdata/slsa/v2alpha4/task-output-image.json
  test/testdata/slsa/v2alpha4/task-with-object-type-hinting.json
Labels: lgtm, size/XXL, approved

#1136 Bump patch release version
  releases.md
Labels: size/XS, lgtm, kind/documentation, approved

#1143 fix e2e
  .github/workflows/kind-e2e.yaml
  .github/workflows/reusable-e2e.yaml
Labels: lgtm, size/S, approved

#1145 Include the ServiceAccount running a pipeline in the chains provenance
  pkg/chains/formats/slsa/v1/intotoite6_test.go
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
  test/testdata/slsa/v1/pipeline-output-image.json
Labels: size/M, lgtm, approved
