Repository tektoncd/chains, pull requests merged in 2024-05, with the labels that each got.

#1109 Move external paramenters and resolved dependencies logic out of v2alpha3
  pkg/chains/formats/slsa/internal/external_parameters/external_parameters.go
  pkg/chains/formats/slsa/internal/external_parameters/external_parameters_test.go
  pkg/chains/formats/slsa/internal/resolved_dependencies/resolved_dependencies.go
  pkg/chains/formats/slsa/internal/resolved_dependencies/resolved_dependencies_test.go
  pkg/chains/formats/slsa/testdata/slsa-v2alpha3/pipelinerun-remote-resolver.json
  pkg/chains/formats/slsa/testdata/slsa-v2alpha3/taskrun-remote-resolver.json
  pkg/chains/formats/slsa/v2alpha3/internal/external_parameters/external_parameters.go
  pkg/chains/formats/slsa/v2alpha3/internal/external_parameters/external_parameters_test.go
  pkg/chains/formats/slsa/v2alpha3/internal/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v2alpha3/internal/pipelinerun/pipelinerun_test.go
  pkg/chains/formats/slsa/v2alpha3/internal/resolved_dependencies/resolved_dependencies.go
  pkg/chains/formats/slsa/v2alpha3/internal/resolved_dependencies/resolved_dependencies_test.go
  pkg/chains/formats/slsa/v2alpha3/internal/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha3/internal/taskrun/taskrun_test.go
Labels: lgtm, size/XXL, approved, ok-to-test

#1112 Update metrics documentation with the prefix
  docs/metrics.md
Labels: lgtm, size/S, kind/documentation, approved

#1100 Make chains QPS and Burst configuration consistent
  cmd/controller/main.go
Labels: size/XS, lgtm, approved, kind/misc

#1119 Configure depguard with "lax" mode
  .golangci.yaml
Labels: size/XS, lgtm, approved

#1121 Set readOnlyRootFilesystem as true in Controller Deployment
  config/100-deployment.yaml
Labels: size/XS, lgtm, approved, kind/security

#1122 Deprecate v2alpha1 and v2alpha2
  docs/config.md
  pkg/chains/formats/all/all.go
  pkg/chains/formats/format.go
  pkg/chains/formats/slsa/README.md
  pkg/chains/formats/slsa/v2alpha1/README.md
  pkg/chains/formats/slsa/v2alpha1/slsav2.go
  pkg/chains/formats/slsa/v2alpha1/slsav2_test.go
  pkg/chains/formats/slsa/v2alpha1/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha1/taskrun/taskrun_test.go
  pkg/chains/formats/slsa/v2alpha2/internal/external_parameters/external_parameters.go
  pkg/chains/formats/slsa/v2alpha2/internal/external_parameters/external_parameters_test.go
  pkg/chains/formats/slsa/v2alpha2/internal/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v2alpha2/internal/pipelinerun/pipelinerun_test.go
  pkg/chains/formats/slsa/v2alpha2/internal/resolved_dependencies/resolved_dependencies.go
  pkg/chains/formats/slsa/v2alpha2/internal/resolved_dependencies/resolved_dependencies_test.go
  pkg/chains/formats/slsa/v2alpha2/internal/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha2/internal/taskrun/taskrun_test.go
  pkg/chains/formats/slsa/v2alpha2/slsav2.go
  pkg/chains/formats/slsa/v2alpha2/slsav2_test.go
  pkg/config/config.go
  test/examples_test.go
  test/testdata/slsa/v2alpha2/pipeline-output-image.json
  test/testdata/slsa/v2alpha2/task-output-image.json
Labels: lgtm, size/XXL, approved, ok-to-test

#1126 Release v0.21.0 made.
  releases.md
Labels: lgtm, size/S, kind/documentation, approved
