Repository tektoncd/chains, pull requests merged in 2024-07, with the labels that each got.

#1151 docs: fix shell snippet
  docs/authentication.md
Labels: size/XS, lgtm, approved, ok-to-test

#1162 Fixes docdb unit test
  pkg/chains/storage/docdb/docdb_test.go
Labels: size/XS, lgtm, approved

#1148 Support multinamespace informer filtering
  cmd/controller/main.go
  docs/config.md
  pkg/reconciler/filter.go
  pkg/reconciler/filter_test.go
  pkg/reconciler/pipelinerun/controller.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
  pkg/reconciler/taskrun/controller.go
  pkg/reconciler/taskrun/taskrun_test.go
Labels: size/XL, lgtm, approved
