Repository tektoncd/chains, pull requests merged in 2024-09, with the labels that each got.

#1188 fix mapping between Status.Steps and Status.TaskSpec.Steps
  pkg/chains/formats/slsa/testdata/pipeline-v1beta1/taskrun4.json
  pkg/chains/formats/slsa/testdata/pipeline-v1beta1/taskrun5.json
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
Labels: size/XL, lgtm, approved

#1194 .github: add github-actions to dependabot…
  .github/dependabot.yml
  .github/workflows/goclean.yml
  .github/workflows/lint.yaml
  .github/workflows/reusable-e2e.yaml
Labels: size/M, lgtm, approved

#1180 Add v0.22.0 release
  releases.md
Labels: size/XS, lgtm, approved

#1203 fix mapping between Status.Steps and Status.TaskSpec.Steps (#1188)
  .github/dependabot.yml
  .github/workflows/goclean.yml
  .github/workflows/lint.yaml
  .github/workflows/reusable-e2e.yaml
  pkg/chains/formats/slsa/testdata/pipeline-v1beta1/taskrun4.json
  pkg/chains/formats/slsa/testdata/pipeline-v1beta1/taskrun5.json
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
Labels: size/XL, lgtm, approved

#1205 Update base image used in ko build
  .ko.yaml
Labels: size/XS, lgtm, approved

#1200 Updates github actions to sync with supported release versions of pipeline and kubernetes
  .github/workflows/kind-e2e.yaml
  test/e2e-tests.sh
Labels: lgtm, size/S, approved

#1206 Disable linter for dependabot PRs
  .github/workflows/lint.yaml
Labels: size/XS, lgtm, approved

#1204 Add v0.22.1 release
  releases.md
Labels: size/XS, lgtm, approved

#1215 Pin images used in the release pipeline
  release/publish.yaml
  release/release-pipeline.yaml
Labels: lgtm, size/S, approved, kind/misc

#1217 Add v0.22.2 release
  releases.md
Labels: size/XS, lgtm, approved
