Repository tektoncd/chains, pull requests merged in 2025-01, with the labels that each got.

#1286 [release-v0.22.x] fix nil pointer
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
Labels: lgtm, size/S, approved

#1273 Bumps golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: size/XS, lgtm, approved, kind/security

#1284 Update go to 1.23 and plumbing vendoring
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/.gitignore
  vendor/github.com/tektoncd/plumbing/OWNERS
  vendor/modules.txt
Labels: size/XS, lgtm, approved, kind/misc

#1291 Copy release resources from main branch v0.22.x
  release/publish.yaml
  release/release-pipeline.yaml
Labels: size/L, lgtm, approved

#1292 Copy release resources from main branch v0.23.x
  release/publish.yaml
  release/release-pipeline.yaml
Labels: lgtm, size/S, approved

#906 Add buildType for Chains format slsa/v2alpha2 (SLSAv1.0 predicate).
  docs/predicate/slsa/v2.md
Labels: size/XL, lgtm, kind/documentation, approved

#1293 Update release info
  release/README.md
  releases.md
Labels: lgtm, size/S, approved
