Repository tektoncd/chains, pull requests merged in 2025-06, with the labels that each got.

#1363 Remove v1beta1 Pipeline API support
  pkg/artifacts/signable.go
  pkg/artifacts/signable_test.go
  pkg/chains/formats/slsa/attest/attest.go
  pkg/chains/formats/slsa/extract/extract.go
  pkg/chains/formats/slsa/extract/v1beta1/extract.go
  pkg/chains/formats/slsa/extract/v1beta1/extract_test.go
  pkg/chains/formats/slsa/internal/build_definition/build_definition_test.go
  pkg/chains/formats/slsa/internal/external_parameters/external_parameters_test.go
  pkg/chains/formats/slsa/internal/internal_parameters/internal_parameters_test.go
  pkg/chains/formats/slsa/internal/material/material.go
  pkg/chains/formats/slsa/internal/material/material_test.go
  pkg/chains/formats/slsa/internal/material/v1beta1/material.go
  pkg/chains/formats/slsa/internal/material/v1beta1/material_test.go
  pkg/chains/formats/slsa/internal/resolved_dependencies/resolved_dependencies.go
  pkg/chains/formats/slsa/internal/resolved_dependencies/resolved_dependencies_test.go
  pkg/chains/formats/slsa/testdata/pipeline-v1/taskrun-multiple-subjects.json
  pkg/chains/formats/slsa/testdata/pipeline-v1/taskrun3.json
  pkg/chains/formats/slsa/testdata/pipeline-v1/taskrun4.json
  pkg/chains/formats/slsa/testdata/pipeline-v1/taskrun5.json
  pkg/chains/formats/slsa/testdata/pipeline-v1beta1/pipelinerun-childrefs.json
  pkg/chains/formats/slsa/testdata/pipeline-v1beta1/pipelinerun1.json
  pkg/chains/formats/slsa/testdata/pipeline-v1beta1/pipelinerun_structured_results.json
  pkg/chains/formats/slsa/testdata/pipeline-v1beta1/taskrun-multiple-subjects.json
  pkg/chains/formats/slsa/testdata/pipeline-v1beta1/taskrun2.json
  pkg/chains/formats/slsa/testdata/pipeline-v1beta1/taskrun4.json
  pkg/chains/formats/slsa/v1/intotoite6.go
  pkg/chains/formats/slsa/v1/intotoite6_test.go
  pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go
  pkg/chains/formats/slsa/v1/pipelinerun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/buildconfig.go
  pkg/chains/formats/slsa/v1/taskrun/buildconfig_test.go
  pkg/chains/formats/slsa/v1/taskrun/provenance_test.go
  pkg/chains/formats/slsa/v1/taskrun/taskrun.go
  pkg/chains/formats/slsa/v2alpha3/internal/pipelinerun/pipelinerun_test.go
  pkg/chains/formats/slsa/v2alpha3/internal/taskrun/taskrun_test.go
  pkg/chains/formats/slsa/v2alpha3/slsav2_test.go
  pkg/chains/formats/slsa/v2alpha4/internal/pipelinerun/pipelinerun_test.go
  pkg/chains/formats/slsa/v2alpha4/internal/taskrun/taskrun_test.go
  pkg/chains/formats/slsa/v2alpha4/slsav2_test.go
  pkg/chains/objects/objects.go
  pkg/chains/storage/docdb/docdb_test.go
  pkg/chains/storage/gcs/gcs.go
  pkg/chains/storage/gcs/gcs_test.go
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/chains/storage/oci/oci_test.go
  pkg/chains/storage/pubsub/pubsub_test.go
  pkg/chains/storage/tekton/tekton_test.go
  pkg/chains/verifier.go
  pkg/internal/objectloader/objectloader.go
  pkg/test/tekton/tekton.go
  test/e2e_test.go
  test/test_utils.go
Labels: size/XXL, approved

#1375 chore: make function comment match function name
  pkg/chains/storage/tekton/tekton.go
Labels: size/XS, lgtm, approved, ok-to-test

#1325 feat: add error metrics for PipelineRun and TaskRun signing failures
  docs/metrics.md
  pkg/chains/constants.go
  pkg/chains/signing.go
  pkg/metrics/common.go
  pkg/pipelinerunmetrics/metrics.go
  pkg/pipelinerunmetrics/metrics_test.go
  pkg/taskrunmetrics/metrics.go
  pkg/taskrunmetrics/metrics_test.go
Labels: size/L, lgtm, approved, ok-to-test

#1380 refactor: use slices.Contains to simplify code
  pkg/reconciler/filter.go
Labels: needs-ok-to-test, size/S, approved

#1386 Enable Integration tests in GH actions
  .github/workflows/kind-e2e.yaml
  .github/workflows/reusable-e2e.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: size/M, lgtm, approved
