Repository tektoncd/chains, pull requests merged in 2025-04, with the labels that each got.

#1330 Consume release pipeline images and task bundles from GHCR
  release/publish.yaml
  release/release-pipeline.yaml
Labels: lgtm, size/S, approved, kind/misc

#1323 chore: make function comment match function name
  pkg/chains/formats/slsa/internal/resolved_dependencies/resolved_dependencies.go
  pkg/chains/storage/docdb/docdb.go
  pkg/chains/storage/tekton/tekton.go
Labels: size/XS, lgtm, approved, ok-to-test

#1333 Add KUBERNETES_MIN_VERSION env to override k8s variable
  config/100-deployment.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#1335 Add ghcr.io migration banner to README.md.
  README.md
Labels: size/XS, lgtm, kind/documentation, approved, ok-to-test

#1342 drop imagePullSecrets for OCI backend (refs #1336)
  pkg/chains/objects/objects.go
  pkg/chains/objects/objects_test.go
  pkg/chains/storage/oci/legacy.go
Labels: size/L, lgtm, approved

#1343 chore: remove duplicate package imports
  pkg/chains/storage/grafeas/grafeas_test.go
  pkg/reconciler/pipelinerun/pipelinerun_test.go
Labels: size/XS, lgtm, approved, ok-to-test
