Repository tektoncd/chains, pull requests merged in 2025-07, with the labels that each got.

#1394 Remove old taskrun finalizer
  pkg/reconciler/taskrun/taskrun.go
Labels: kind/bug, lgtm, size/S, approved

#1400 Fix link to keyless signing doc
  docs/signing.md
Labels: size/XS, lgtm, kind/documentation, approved

#1395 Handle signing and attesting blobs
  pkg/chains/storage/oci/attestation.go
  pkg/chains/storage/oci/attestation_test.go
  pkg/chains/storage/oci/simple.go
  pkg/chains/storage/oci/simple_test.go
  vendor/github.com/google/go-containerregistry/pkg/v1/random/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/random/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/random/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/random/options.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#1401 Update the kind-e2e.yaml for latest and LTS
  .github/workflows/kind-e2e.yaml
  .github/workflows/reusable-e2e.yaml
Labels: lgtm, size/S, approved

#1365 fix: improve error handling during OCI auth initialization
  pkg/chains/storage/oci/legacy.go
Labels: size/XS, lgtm, approved, ok-to-test
