Repository tektoncd/chains, pull requests merged in 2025-05, with the labels that each got.

#1316 Add Archivista Storage Backend
  docs/config.md
  go.mod
  go.sum
  pkg/chains/storage/archivista/archivista.go
  pkg/chains/storage/archivista/archivista_test.go
  pkg/chains/storage/storage.go
  pkg/config/config.go
  vendor/github.com/edwarnicke/gitoid/.gitignore
  vendor/github.com/edwarnicke/gitoid/LICENSE
  vendor/github.com/edwarnicke/gitoid/README.md
  vendor/github.com/edwarnicke/gitoid/gitoid.go
  vendor/github.com/edwarnicke/gitoid/options.go
  vendor/github.com/in-toto/archivista/LICENSE
  vendor/github.com/in-toto/archivista/pkg/api/download.go
  vendor/github.com/in-toto/archivista/pkg/api/graphql.go
  vendor/github.com/in-toto/archivista/pkg/api/structs.go
  vendor/github.com/in-toto/archivista/pkg/api/upload.go
  vendor/github.com/in-toto/archivista/pkg/http-client/client.go
  vendor/github.com/in-toto/go-witness/LICENSE
  vendor/github.com/in-toto/go-witness/cryptoutil/digestset.go
  vendor/github.com/in-toto/go-witness/cryptoutil/dirhash.go
  vendor/github.com/in-toto/go-witness/cryptoutil/ecdsa.go
  vendor/github.com/in-toto/go-witness/cryptoutil/ed25519.go
  vendor/github.com/in-toto/go-witness/cryptoutil/gitoid.go
  vendor/github.com/in-toto/go-witness/cryptoutil/rsa.go
  vendor/github.com/in-toto/go-witness/cryptoutil/signer.go
  vendor/github.com/in-toto/go-witness/cryptoutil/util.go
  vendor/github.com/in-toto/go-witness/cryptoutil/verifier.go
  vendor/github.com/in-toto/go-witness/cryptoutil/x509.go
  vendor/github.com/in-toto/go-witness/dsse/dsse.go
  vendor/github.com/in-toto/go-witness/dsse/sign.go
  vendor/github.com/in-toto/go-witness/dsse/verify.go
  vendor/github.com/in-toto/go-witness/log/log.go
  vendor/github.com/in-toto/go-witness/log/silent.go
  vendor/github.com/in-toto/go-witness/timestamp/fake.go
  vendor/github.com/in-toto/go-witness/timestamp/timestamp.go
  vendor/github.com/in-toto/go-witness/timestamp/tsp.go
  vendor/golang.org/x/mod/sumdb/dirhash/hash.go
  vendor/modules.txt
Labels: size/L, lgtm, approved, ok-to-test

#1353 Update release.md to include v0.25.0 version of chains
  releases.md
Labels: size/XS, lgtm, approved

#1357 Update go mod to use Go 1.23
  go.mod
  go.sum
  vendor/gocloud.dev/aws/aws.go
  vendor/gocloud.dev/docstore/awsdynamodb/dynamo.go
  vendor/gocloud.dev/docstore/doc.go
  vendor/gocloud.dev/docstore/docstore.go
  vendor/gocloud.dev/docstore/driver/driver.go
  vendor/gocloud.dev/docstore/driver/util.go
  vendor/gocloud.dev/docstore/gcpfirestore/fs.go
  vendor/gocloud.dev/docstore/memdocstore/mem.go
  vendor/gocloud.dev/docstore/mongodocstore/docker-compose.yml
  vendor/gocloud.dev/docstore/mongodocstore/localmongo.sh
  vendor/gocloud.dev/docstore/mongodocstore/mongo.go
  vendor/gocloud.dev/internal/gcerr/gcerr.go
  vendor/gocloud.dev/internal/oc/trace.go
  vendor/gocloud.dev/internal/openurl/openurl.go
  vendor/gocloud.dev/internal/useragent/useragent.go
  vendor/gocloud.dev/pubsub/batcher/batcher.go
  vendor/gocloud.dev/pubsub/driver/driver.go
  vendor/gocloud.dev/pubsub/kafkapubsub/kafka.go
  vendor/gocloud.dev/pubsub/mempubsub/mem.go
  vendor/gocloud.dev/pubsub/pubsub.go
  vendor/modules.txt
Labels: lgtm, size/S, approved

#1358 Fix subpath capitalisation
  release/release-pipeline.yaml
Labels: lgtm, size/S, approved, kind/misc
